/**
 * The app's piece sets and the CSS that carries them (see scripts/generate-pieces.mjs, which
 * writes it, and pieces.test.ts, which checks the written files are current).
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as bold from './bold.mjs';
import * as letters from './letters.mjs';
import * as modern from './modern.mjs';
import * as pixel from './pixel.mjs';
import * as staunton from './staunton.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

export const ROLES = ['king', 'queen', 'rook', 'bishop', 'knight', 'pawn'];
export const COLORS = ['white', 'black'];

/* ------------------------------------------------------------------ */
/* Classic: the cburnett set that ships with Chessground, re-emitted   */
/* with the shared selectors so previews can show it next to the rest. */
/* ------------------------------------------------------------------ */
const CBURNETT = readFileSync(
  join(ROOT, 'node_modules', '@lichess-org', 'chessground', 'assets', 'chessground.cburnett.css'),
  'utf8',
);

function classicUri(role, color) {
  const rule = new RegExp(
    `\\.cg-wrap piece\\.${role}\\.${color} \\{\\s*background-image: url\\('([^']+)'\\)`,
  );
  const match = CBURNETT.match(rule);
  if (!match) throw new Error(`cburnett: no image for ${color} ${role}`);
  return match[1];
}

/**
 * A data URI for an SVG inside a single-quoted CSS url(): only the characters that would end
 * the string or confuse the URL parser are escaped, which keeps the CSS small.
 */
function svgUri(svg) {
  if (svg.includes("'")) throw new Error('an SVG for a CSS url() must not contain single quotes');
  return `data:image/svg+xml,${svg.replace(/[%#<>]/g, (c) => encodeURIComponent(c))}`;
}

export const SETS = [
  {
    id: 'classic',
    uri: classicUri,
    description:
      "Colin M.L. Burnett's figurines, from the Chessground package (see THIRD_PARTY_NOTICES.md).",
    isDefault: true,
  },
  {
    id: 'staunton',
    draw: staunton.draw,
    description: 'original tournament shapes with a heavier line, crisp on a phone.',
  },
  {
    id: 'bold',
    draw: bold.draw,
    description:
      'original big, simple shapes with a heavy outline; black pieces carry a light rim.',
  },
  {
    id: 'modern',
    draw: modern.draw,
    description: 'original plain geometry with one line weight.',
  },
  {
    id: 'pixel',
    draw: pixel.draw,
    description: 'an original 8-bit set drawn on a 16×16 grid, with crisp edges at any size.',
  },
  {
    id: 'letters',
    draw: letters.draw,
    description: "the piece's initial, drawn as paths so it looks the same on every device.",
  },
];

/**
 * The stylesheet for one set: twelve rules, one per piece.
 * @param {{
 *   id: string,
 *   description: string,
 *   isDefault?: boolean,
 *   uri?: (role: string, color: string) => string,
 *   draw?: (role: string, color: string) => string,
 * }} set
 */
export function pieceCss({ id, uri, draw, description, isDefault = false }) {
  const uriOf = uri ?? ((role, color) => svgUri(draw(role, color)));
  const rules = [];
  for (const color of COLORS) {
    for (const role of ROLES) {
      const selectors = [
        isDefault ? `.cg-wrap piece.${color}.${role}` : null,
        `[data-pieces='${id}'] piece.${color}.${role}`,
        `.piece-preview.pieces-${id} piece.${color}.${role}`,
      ].filter(Boolean);
      rules.push(
        `${selectors.join(',\n')} {\n  background-image: url('${uriOf(role, color)}');\n}`,
      );
    }
  }
  return (
    `/*\n * "${id[0].toUpperCase()}${id.slice(1)}" piece set: ${description}\n` +
    ` * Generated by scripts/generate-pieces.mjs — edit the script, not this file.\n` +
    ` * Selected with data-pieces="${id}" on <html> (see components/board/pieceSets.ts);\n` +
    ` * .piece-preview.pieces-${id} shows it inside one element.\n */\n` +
    rules.join('\n\n') +
    '\n'
  );
}
