/**
 * The app's piece sets and the CSS that carries them (scripts/generate-pieces.mjs writes it,
 * pieces.test.ts checks the written files are current). The sets themselves live in
 * src/components/board/pieces/, one folder of twelve SVGs each, with their sources and licences.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

/** Where the sets' SVGs are and where their stylesheets are written. */
export const PIECES_DIR = join(ROOT, 'src', 'components', 'board', 'pieces');

export const ROLES = ['king', 'queen', 'rook', 'bishop', 'knight', 'pawn'];
export const COLORS = ['white', 'black'];
const LETTER = { king: 'K', queen: 'Q', rook: 'R', bishop: 'B', knight: 'N', pawn: 'P' };

/* ------------------------------------------------------------------ */
/* Classic: the cburnett set that ships with Chessground, re-emitted   */
/* with the shared selectors so previews can show it next to the rest. */
/* ------------------------------------------------------------------ */
const CBURNETT = readFileSync(
  join(ROOT, 'node_modules', '@lichess-org', 'chessground', 'assets', 'chessground.cburnett.css'),
  'utf8',
);

function classicUri(role, color) {
  const rule = new RegExp(
    `\\.cg-wrap piece\\.${role}\\.${color} \\{\\s*background-image: url\\('([^']+)'\\)`,
  );
  const match = CBURNETT.match(rule);
  if (!match) throw new Error(`cburnett: no image for ${color} ${role}`);
  return match[1];
}

/**
 * A data URI for an SVG inside a single-quoted CSS url(): only the characters that would end
 * the string, break the line or confuse the URL parser are escaped, which keeps the CSS small.
 */
export function svgUri(svg) {
  if (svg.includes("'")) throw new Error('an SVG for a CSS url() must not contain single quotes');
  return `data:image/svg+xml,${svg.replace(/[%#<>\r\n]/g, (c) => encodeURIComponent(c))}`;
}

/** The file of one piece of a set, as Lichess names it: wK.svg is the white king. */
export function pieceFile(id, role, color) {
  return join(PIECES_DIR, id, `${color[0]}${LETTER[role]}.svg`);
}

/**
 * Every set the app offers, Classic first. A set's description heads its stylesheet; see
 * src/components/board/pieces/README.md for the sources and licences.
 */
export const SETS = [
  {
    id: 'classic',
    uri: classicUri,
    description:
      "Colin M.L. Burnett's figurines (cburnett, CC BY-SA 3.0), from the Chessground package.",
    isDefault: true,
  },
  { id: 'merida', description: 'by Armando Hernandez Marroquin, GPL-2.0-or-later.' },
  { id: 'chessnut', description: 'by Alexis Luengas, Apache-2.0.' },
  { id: 'mpchess', description: 'by Maxime Chupin, GPL-3.0-or-later.' },
  { id: 'celtic', description: 'by Maurizio Monge, MIT.' },
  { id: 'california', description: 'by Jerry S., CC BY-NC-SA 4.0: non-commercial use only.' },
  { id: 'maestro', description: 'by sadsnake1, CC BY-NC-SA 4.0: non-commercial use only.' },
  { id: 'staunty', description: 'by sadsnake1, CC BY-NC-SA 4.0: non-commercial use only.' },
  { id: 'cardinal', description: 'by sadsnake1, CC BY-NC-SA 4.0: non-commercial use only.' },
];

/**
 * The stylesheet for one set: twelve rules, one per piece.
 * @param {{
 *   id: string,
 *   description: string,
 *   isDefault?: boolean,
 *   uri?: (role: string, color: string) => string,
 * }} set
 */
export function pieceCss({ id, uri, description, isDefault = false }) {
  const uriOf = uri ?? ((role, color) => svgUri(readFileSync(pieceFile(id, role, color), 'utf8')));
  const rules = [];
  for (const color of COLORS) {
    for (const role of ROLES) {
      const selectors = [
        isDefault ? `.cg-wrap piece.${color}.${role}` : null,
        `[data-pieces='${id}'] piece.${color}.${role}`,
        `.piece-preview.pieces-${id} piece.${color}.${role}`,
      ].filter(Boolean);
      rules.push(
        `${selectors.join(',\n')} {\n  background-image: url('${uriOf(role, color)}');\n}`,
      );
    }
  }
  const lines = [`"${id[0].toUpperCase()}${id.slice(1)}" piece set: ${description}`];
  if (!isDefault) lines.push('From the Lichess repository: see README.md beside this file.');
  lines.push(
    'Generated by scripts/generate-pieces.mjs — edit the script or the SVGs, not this file.',
    `Selected with data-pieces="${id}" on <html> (see components/board/pieceSets.ts);`,
    `.piece-preview.pieces-${id} shows it inside one element.`,
  );
  return `/*\n${lines.map((line) => ` * ${line}`).join('\n')}\n */\n${rules.join('\n\n')}\n`;
}
