import type { ClassicGame } from './games';

/** Third set of classic games: miniatures from the earliest masters to the Karpov era. */
export const CLASSIC_GAMES_3: readonly ClassicGame[] = [
  {
    id: 'legall-saint-brie',
    title: 'Légal’s mate',
    white: 'Kermur Sire de Légal',
    black: 'Saint Brie',
    event: 'Café de la Régence, Paris (odds game)',
    year: 1750,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 8,
    difficulty: 1,
    intro:
      'The oldest trap with a name. Légal, the strongest player in Paris before Philidor, lets his queen be taken — and mates with three minor pieces. Every player should know the pattern.',
    moves: 'e4 e5 Bc4 d6 Nf3 Nc6 Nc3 Bg4 Nxe5 Bxd1 Bxf7+ Ke7 Nd5#',
    notes: {
      9: 'Nxe5! The pin on the f3-knight looked natural, but a knight is not really pinned when the queen is worth less than a mate. The threats are Nxg4 and, more to the point, Bxf7+.',
      11: 'Black took the queen (5...dxe5 6.Qxg4 would only have lost a pawn) — and Bxf7+ drags the king to e7, the only square.',
      13: 'Nd5 mate: the knight covers e7’s neighbours together with the bishop and the e5-knight. Three minor pieces against a queen — and a king.',
    },
    outro:
      'The pattern needs three things: a bishop on c4, a knight that can reach d5 (or f5) with a mating net, and a black bishop on g4 that gets greedy. Look for it when you play the Italian.',
  },
  {
    id: 'mcdonnell-la-bourdonnais',
    title: 'Three pawns on the seventh',
    white: 'Alexander McDonnell',
    black: 'Louis-Charles de La Bourdonnais',
    event: 'Match, London (4th match, game 16)',
    year: 1834,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 7,
    difficulty: 3,
    intro:
      'The first great chess match, eighty-five games between the best players of France and Britain. This is its most famous game: La Bourdonnais gives up material for a mass of central pawns that end up on the second rank, and no piece can stop them.',
    moves:
      'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 e5 Nxc6 bxc6 Bc4 Nf6 Bg5 Be7 Qe2 d5 Bxf6 Bxf6 Bb3 O-O O-O a5 exd5 cxd5 Rd1 d4 c4 Qb6 Bc2 Bb7 Nd2 Rae8 Ne4 Bd8 c5 Qc6 f3 Be7 Rac1 f5 Qc4+ Kh8 Ba4 Qh6 Bxe8 fxe4 c6 exf3 Rc2 Qe3+ Kh1 Bc8 Bd7 f2 Rf1 d3 Rc3 Bxd7 cxd7 e4 Qc8 Bd8 Qc4 Qe1 Rc1 d2 Qc5 Rg8 Rd1 e3 Qc3 Qxd1 Rxd1 e2',
    notes: {
      8: 'Kicking the knight with ...e5 — a bold idea in 1834. Black accepts a weak d5-square for a big centre.',
      16: '...d5 in one go. The doubled c-pawns turn into a pawn centre.',
      26: 'The pawn reaches d4 and the centre starts to roll. The bishop pair and the passed pawn are Black’s compensation for the loose pieces.',
      32: 'Rae8: every rook joins in. Black has no interest in the a-pawn; the fight is in the centre.',
      40: '...f5! opens the position while the white king is stuck behind the pawn wall.',
      44: '...Qh6! Black lets the rook on e8 go: after Bxe8 fxe4 the knight is gone too and the pawn mass starts to roll.',
      50: 'Qe3+ and the pawns go forward with tempo. Count them: e4, f3 and d4 against a bare king.',
      54: 'f2: the first pawn reaches the seventh. White’s rook and queen are tied to stopping promotions.',
      64: 'Qe1! trades queens into a won ending — or rather, into three pawns that decide by themselves.',
      74: 'Three pawns on the second rank — d2, e2 and f2 — and White resigned. No rook, no queen can cover all three queening squares.',
    },
    outro:
      'A pawn mass supported by pieces is worth more than the material it cost. Notice how Black never hurried: the pieces went to their best squares first, then the pawns marched.',
  },
  {
    id: 'steinitz-mongredien',
    title: 'Steinitz sacrifices on h7',
    white: 'Wilhelm Steinitz',
    black: 'Augustus Mongredien',
    event: 'London (B.C.A. Grand Tourney)',
    year: 1862,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 16,
    difficulty: 2,
    intro:
      'Before he invented positional chess, Steinitz was a fearsome attacker. Here he lifts a rook to h3, sacrifices it on h7 and chases the king across the board — every move a check or a threat.',
    moves:
      'e4 d5 exd5 Qxd5 Nc3 Qd8 d4 e6 Nf3 Nf6 Bd3 Be7 O-O O-O Be3 b6 Ne5 Bb7 f4 Nbd7 Qe2 Nd5 Nxd5 exd5 Rf3 f5 Rh3 g6 g4 fxg4 Rxh7 Nxe5 fxe5 Kxh7 Qxg4 Rg8 Qh5+ Kg7 Qh6+ Kf7 Qh7+ Ke6 Qh3+ Kf7 Rf1+ Ke8 Qe6 Rg7 Bg5 Qd7 Bxg6+ Rxg6 Qxg6+ Kd8 Rf8+ Qe8 Qxe8#',
    notes: {
      17: 'A knight on e5 and a pawn coming to f4: the classic Steinitz set-up against a castled king.',
      25: 'The rook lift Rf3–h3 aims straight at h7. Black’s ...f5 has just weakened the diagonal a2–g8.',
      29: 'g4! opens the g-file and drags the f-pawn away from the king.',
      31: 'Rxh7! Black cannot take at once (...Kxh7 Qxg4 and Qh5+ follows), and after ...Nxe5 fxe5 Kxh7 Qxg4 the king stands in the open with the g-file half open.',
      35: 'Qxg4 threatens Qh5+ and Qxg8. Every white piece is aimed at the king.',
      45: 'Rf1+ brings the last piece in with tempo. The king has to go back to e8, into a mating net.',
      47: 'Qe6 — a quiet move in the middle of a king hunt. It threatens Bg5 and Bxg6+, and there is no defence.',
      57: 'Mate on e8. Count the checks from move 19 onwards: the attack never gave Black a free move.',
    },
    outro:
      'The rook lift, the pawn lever g4 and the sacrifice on h7 all belong to one plan: open lines towards the king before the defender can consolidate.',
  },
  {
    id: 'hamppe-meitner',
    title: 'The Immortal Draw',
    white: 'Carl Hamppe',
    black: 'Philipp Meitner',
    event: 'Vienna',
    year: 1872,
    result: '1/2-1/2',
    guessColor: 'black',
    guessFromPly: 5,
    difficulty: 3,
    intro:
      'A king hunt that ends in a draw by perpetual check — with the white king on c6 in the middle of Black’s position. Meitner sacrifices a bishop, a queen and a knight to get there. The most entertaining draw ever played.',
    moves:
      'e4 e5 Nc3 Bc5 Na4 Bxf2+ Kxf2 Qh4+ Ke3 Qf4+ Kd3 d5 Kc3 Qxe4 Kb3 Na6 a3 Qxa4+ Kxa4 Nc5+ Kb4 a5+ Kxc5 Ne7 Bb5+ Kd8 Bc6 b6+ Kb5 Nxc6 Kxc6 Bb7+ Kb5 Ba6+ Kc6',
    notes: {
      6: 'Bxf2+!? drags the king out. It is not the best move — but it starts the show.',
      8: 'Qh4+ and the king has to walk: g3 would lose the rook on h1.',
      12: '...d5 opens the c8-bishop and takes the e4-pawn under fire.',
      14: 'Qxe4: a pawn and a king in the open for the bishop.',
      16: '...Na6 threatens ...Qb4 mate.',
      18: 'The queen sacrifice Qxa4+!! The king must take, and now every black piece comes with check.',
      20: 'Nc5+ with tempo. Notice how the black king, safe at home, never moved.',
      22: 'a5+ keeps the king walking forward — into the black camp.',
      24: '...Ne7 — a quiet developing move in the middle of the storm, preparing ...b6+ and ...Nxc6 to close the net.',
      28: '...b6+ drives the king back to b5, and the c6-bishop that shielded it is about to disappear.',
      34: 'Ba6+ and the bishop shuffles between b7 and a6 for ever: White cannot escape the checks without losing the king.',
    },
    outro:
      'A draw, but a lesson in initiative: once the king is dragged into the open, every developing move comes with check. Also a lesson in defence — Hamppe found the only squares each time.',
  },
  {
    id: 'rubinstein-lasker-1909',
    title: 'Rubinstein outplays the champion',
    white: 'Akiba Rubinstein',
    black: 'Emanuel Lasker',
    event: 'St Petersburg',
    year: 1909,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 16,
    difficulty: 3,
    intro:
      'Rubinstein beats the world champion with a combination in the opening and a textbook rook ending. Watch how a small tactical edge is turned into a pawn, and the pawn into a win.',
    moves:
      'd4 d5 Nf3 Nf6 c4 e6 Bg5 c5 cxd5 exd5 Nc3 cxd4 Nxd4 Nc6 e3 Be7 Bb5 Bd7 Bxf6 Bxf6 Nxd5 Bxd4 exd4 Qg5 Bxc6 Bxc6 Ne3 O-O-O O-O Rhe8 Rc1 Rxe3 Rxc6+ bxc6 Qc1 Rxd4 fxe3 Rd7 Qxc6+ Kd8 Rf4 f5 Qc5 Qe7 Qxe7+ Kxe7 Rxf5 Rd1+ Kf2 Rd2+ Kf3 Rxb2 Ra5 Rb7 Ra6 Kf8 e4 Rc7 h4 Kf7 g4 Kf8 Kf4 Ke7 h5 h6 Kf5 Kf7 e5 Rb7 Rd6 Ke7 Ra6 Kf7 Rd6 Kf8 Rc6 Kf7 a3',
    notes: {
      17: 'Bb5 pins the knight and prepares the little combination on d5.',
      21: 'Nxd5! takes a pawn: 11...Bxd5 would lose a piece to 12.Bxc6+, so Lasker takes on d4 and counter-attacks g2 with the queen.',
      27: 'Ne3 keeps everything protected. Lasker has activity for the pawn but no more.',
      31: 'Rc1! — the key move. Black’s ...Rxe3 looks strong, but Rubinstein has seen the counter-blow.',
      33: 'Rxc6+! bxc6 Qc1! — the rook on e3 is attacked, and after ...Rxd4 fxe3 Rd7 Qxc6+ White has come out a pawn ahead with the safer king.',
      39: 'Qxc6+ and White is a clean pawn up with the safer king. Now the technique begins.',
      43: 'Qc5 forces the queens off: the endgame is won and the queens only give Black chances.',
      53: 'Ra5! stops ...a5 and ties the black rook to the a-pawn. Rooks belong behind passed pawns — and beside weak ones.',
      57: 'e4: with the rook tied down, the king and the connected pawns come forward.',
      69: 'e5 and Black’s king can never come to the centre. White will play e6, or Kg6 and Rf6 — Lasker resigned after 40.a3.',
    },
    outro:
      'Rubinstein’s formula: win a pawn with a combination, trade queens, tie a rook to a weak pawn, then march the king. The rook ending is worth replaying on its own.',
  },
  {
    id: 'roesch-schlage',
    title: 'Poole versus HAL 9000',
    white: 'Roesch',
    black: 'Willi Schlage',
    event: 'Hamburg',
    year: 1910,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 15,
    difficulty: 2,
    intro:
      'The game played by the computer HAL against astronaut Frank Poole in 2001: A Space Odyssey — a real game from Hamburg 1910. Black gives a rook for a mating attack with queen and bishop.',
    moves:
      'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 Qe2 b5 Bb3 Be7 c3 O-O O-O d5 exd5 Nxd5 Nxe5 Nf4 Qe4 Nxe5 Qxa8 Qd3 Bd1 Bh3 Qxa6 Bxg2 Re1 Qf3',
    notes: {
      16: '...d5 opens the centre while White’s queen is oddly placed on e2.',
      20: '...Nf4! The knight attacks the queen and eyes g2; it does not care about the e5-knight.',
      22: '...Nxe5 lets the rook go: Black is looking at the white king, not at material.',
      24: '...Qd3! A quiet move that keeps the white queen out of the defence. The threat is ...Bh3, ...Bxg2 and ...Qf3 with mate on g2.',
      26: 'Bh3 threatens ...Bxg2 and mate. White has no way to bring the queen back.',
      28: 'Bxg2 and the king’s cover is gone. Re1 is the only move, allowing …',
      30: '…Qf3, and mate on g2 or h1 cannot be stopped. HAL announced: “Bishop takes knight’s pawn… Queen to bishop three… checkmate.”',
    },
    outro:
      'A rook is a small price for a queen, a bishop and an open king. Before grabbing material far from your king, check what your opponent is threatening near it.',
  },
  {
    id: 'nimzowitsch-alapin',
    title: 'Development beats a queen',
    white: 'Aron Nimzowitsch',
    black: 'Semion Alapin',
    event: 'Riga (casual game)',
    year: 1914,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 16,
    difficulty: 2,
    intro:
      'Black grabs a pawn on g2 with the queen and never gets to castle. Nimzowitsch, the great theorist, demonstrates his own rule: development first. The finish is a queen sacrifice and a rook mate.',
    moves:
      'e4 e6 d4 d5 Nc3 Nf6 exd5 Nxd5 Nf3 c5 Nxd5 Qxd5 Be3 cxd4 Nxd4 a6 Be2 Qxg2 Bf3 Qg6 Qd2 e5 O-O-O exd4 Bxd4 Nc6 Bf6 Qxf6 Rhe1+ Be7 Bxc6+ Kf8 Qd8+ Bxd8 Re8#',
    notes: {
      17: 'Be2 offers the g-pawn. Nimzowitsch is counting tempi, not pawns.',
      19: 'Bf3 gains a tempo on the queen and points at b7 and c6.',
      21: 'Qd2 prepares O-O-O: the rook comes to d1 in one move while Black is still moving the queen.',
      23: 'Castling long with the knight on d4 en prise: after ...exd4 Bxd4 the bishop stands in the centre, the d-file is open and Black’s king is still on e8.',
      27: 'Bf6!! A bishop for a tempo: after ...Qxf6 the rook arrives on e1 with check and the black king cannot get out.',
      29: 'Rhe1+ and there is only one piece to interpose — the bishop that should have castled Black.',
      31: 'Bxc6+ removes the last defender of d8 and e8.',
      33: 'Qd8+! Bxd8 Re8 mate. Count the moves each side spent on development.',
    },
    outro:
      'Nimzowitsch’s own summary: a pawn on g2 is not worth three tempi. Look at the final position — Black’s rooks and bishop never took part.',
  },
  {
    id: 'reti-capablanca-1924',
    title: 'Capablanca loses at last',
    white: 'Richard Réti',
    black: 'José Raúl Capablanca',
    event: 'New York',
    year: 1924,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 20,
    difficulty: 3,
    intro:
      'Capablanca had not lost a serious game in eight years. Réti beat him with the hypermodern opening that bears his name — b4 and Bb2, bishops on the long diagonals, the d- and e-pawns held back so the centre is controlled from the flanks — and a queen sortie punished with a rook invasion.',
    moves:
      'Nf3 Nf6 c4 g6 b4 Bg7 Bb2 O-O g3 b6 Bg2 Bb7 O-O d6 d3 Nbd7 Nbd2 e5 Qc2 Re8 Rfd1 a5 a3 h6 Nf1 c5 b5 Nf8 e3 Qc7 d4 Be4 Qc3 exd4 exd4 N6d7 Qd2 cxd4 Bxd4 Qxc4 Bxg7 Kxg7 Qb2+ Kg8 Rxd6 Qc5 Rad1 Ra7 Ne3 Qh5 Nd4 Bxg2 Kxg2 Qe5 Nc4 Qc5 Nc6 Rc7 Ne3 Ne5 R1d5',
    notes: {
      21: 'Rfd1 — the rook goes to the d-file before the d-pawn moves. Réti prepares d4 slowly.',
      31: 'd4! at the right moment: Black’s pieces are tangled on the queenside and the e5-pawn becomes a target.',
      33: 'Qc3 hits e5 and pins nothing, but every white piece now looks at the centre.',
      37: 'Qd2 keeps the queen out of the exchanges: White wants the position open, not simplified.',
      39: 'Bxd4 — the bishop takes over the long diagonal; ...Qxc4 wins a pawn but takes the queen far from the king.',
      43: 'Qb2+ and Black’s king has to step back while the d6-pawn falls with Rxd6.',
      49: 'Ne3! attacks the queen and heads for d5 and c4. The white pieces coordinate; the black queen is alone.',
      57: 'Nc6 hits the rook on a7 and the a5-pawn at once; the queen on the other wing cannot cover everything.',
      61: 'R1d5! and the queen is trapped: it has no square that is not covered. Capablanca resigned.',
    },
    outro:
      'The hypermodern idea in one game: let the opponent build a centre, then attack it with pieces from a distance. And a tactical lesson — a queen that goes pawn-grabbing can be trapped by knights and rooks.',
  },
  {
    id: 'capablanca-tartakower-1924',
    title: 'The king walks to victory',
    white: 'José Raúl Capablanca',
    black: 'Savielly Tartakower',
    event: 'New York',
    year: 1924,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 52,
    difficulty: 2,
    intro:
      'The most famous rook ending of all. Capablanca gives up two pawns to bring his king to f6 — in front of his own passed pawn, next to the enemy king — and the rest plays itself.',
    moves:
      'd4 e6 Nf3 f5 c4 Nf6 Bg5 Be7 Nc3 O-O e3 b6 Bd3 Bb7 O-O Qe8 Qe2 Ne4 Bxe7 Nxc3 bxc3 Qxe7 a4 Bxf3 Qxf3 Nc6 Rfb1 Rae8 Qh3 Rf6 f4 Na5 Qf3 d6 Re1 Qd7 e4 fxe4 Qxe4 g6 g3 Kf8 Kg2 Rf7 h4 d5 cxd5 exd5 Qxe8+ Qxe8 Rxe8+ Kxe8 h5 Rf6 hxg6 hxg6 Rh1 Kf8 Rh7 Rc6 g4 Nc4 g5 Ne3+ Kf3 Nf5 Bxf5 gxf5 Kg3 Rxc3+ Kh4 Rf3 g6 Rxf4+ Kg5 Re4 Kf6 Kg8 Rg7+ Kh8 Rxc7 Re8 Kxf5 Re4 Kf6 Rf4+ Ke5 Rg4 g7+ Kg8 Rxa7 Rg1 Kxd5 Rc1 Kd6 Rc2 d5 Rc1 Rc7 Ra1 Kc6 Rxa4 d6',
    notes: {
      53: 'h5! The h-pawn is offered to open the h-file for the rook: activity before material.',
      57: 'Rh1 — the rook reaches the open file and heads for the seventh rank.',
      59: 'Rh7 cuts the king off on the back rank and attacks c7.',
      63: 'g5! Capablanca ignores the knight’s counterplay: the pawns and king are coming.',
      69: 'Kg3! The king starts its walk. Black takes on c3 — the first pawn given away.',
      71: 'Kh4 — and the f-pawn goes too. Two pawns for a king on g5 next to the passed g-pawn.',
      75: 'Kg5, then Kf6: the king protects the g-pawn and attacks the black king at the same time.',
      77: 'Kf6! The picture Capablanca was aiming for: king in front of the pawn, rook on the seventh, Black’s king helpless on g8.',
      79: 'Rg7+ drives the king into the corner; then Rxc7 and the rook returns to collect pawns while the king holds everything.',
      89: 'g7+ fixes the king on g8. Every black move from here is forced.',
      97: 'd5, d6 — the second passed pawn decides. Tartakower resigned after 52.d6.',
    },
    outro:
      'In rook endings the king is a fighting piece. Capablanca counted that two pawns were a fair price for a king on f6 and a rook on the seventh — and he was right.',
  },
  {
    id: 'reti-alekhine-1925',
    title: 'Alekhine’s knight tour',
    white: 'Richard Réti',
    black: 'Alexander Alekhine',
    event: 'Baden-Baden',
    year: 1925,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 51,
    difficulty: 3,
    intro:
      'Alekhine’s most famous game: a rook goes to e3 and cannot be taken, a knight tours the board with check after check, and the combination ends fourteen moves later with a fork. Calculate along with him.',
    moves:
      'g3 e5 Nf3 e4 Nd4 d5 d3 exd3 Qxd3 Nf6 Bg2 Bb4+ Bd2 Bxd2+ Nxd2 O-O c4 Na6 cxd5 Nb4 Qc4 Nbxd5 N2b3 c6 O-O Re8 Rfd1 Bg4 Rd2 Qc8 Nc5 Bh3 Bf3 Bg4 Bg2 Bh3 Bf3 Bg4 Bh1 h5 b4 a6 Rc1 h4 a4 hxg3 hxg3 Qc7 b5 axb5 axb5 Re3 Nf3 cxb5 Qxb5 Nc3 Qxb7 Qxb7 Nxb7 Nxe2+ Kh2 Ne4 Rc4 Nxf2 Bg2 Be6 Rcc2 Ng4+ Kh3 Ne5+ Kh2 Rxf3 Rxe2 Ng4+ Kh3 Ne3+ Kh2 Nxc2 Bxf3 Nd4',
    notes: {
      52: 'Re3!! The rook cannot be taken: fxe3 Qxg3+ and mate on h2. Réti plays Nf3 to hold it.',
      56: '...Nc3! The knight jumps into the fire: it attacks the queen and threatens ...Nxe2+.',
      58: 'Queens off — but the combination continues. Alekhine has seen the fork at the end.',
      60: '...Nxe2+ wins a pawn with check; the knight will not stop moving for six moves.',
      62: '...Ne4! attacks the rook on d2 and f2. White’s pieces are all on the queenside.',
      64: '...Nxf2: a second pawn, and the knight is already looking at ...Ng4+ and ...Ne5+ — the checks that will carry it to the fork.',
      66: '...Be6 hits the rook on c4; the rook must leave the fourth rank.',
      68: '...Ng4+ starts the final sequence: every move a check until the fork.',
      72: '...Rxf3! The rook is given back with interest: after Rxe2 the knight checks again.',
      78: '...Nxc2 — a rook and two pawns for the rook. Réti’s Bxf3 hopes for the exchange, but …',
      80: '…Nd4! forks bishop and rook. The knight that started on b4 on move 10 wins the game on move 40.',
    },
    outro:
      'Fourteen moves of forcing play, and Alekhine had to see the final fork before playing ...Re3. When you find a knight with many checks, look for the fork at the end of the line.',
  },
  {
    id: 'torre-lasker-1925',
    title: 'The windmill',
    white: 'Carlos Torre',
    black: 'Emanuel Lasker',
    event: 'Moscow',
    year: 1925,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 48,
    difficulty: 2,
    intro:
      'The most famous windmill ever: a rook and a bishop take turns giving check, and the rook eats a whole row of pieces on its way. Torre gives his queen for it — against the former world champion.',
    moves:
      'd4 Nf6 Nf3 e6 Bg5 c5 e3 cxd4 exd4 Be7 Nbd2 d6 c3 Nbd7 Bd3 b6 Nc4 Bb7 Qe2 Qc7 O-O O-O Rfe1 Rfe8 Rad1 Nf8 Bc1 Nd5 Ng5 b5 Na3 b4 cxb4 Nxb4 Qh5 Bxg5 Bxg5 Nxd3 Rxd3 Qa5 b4 Qf5 Rg3 h6 Nc4 Qd5 Ne3 Qb5 Bf6 Qxh5 Rxg7+ Kh8 Rxf7+ Kg8 Rg7+ Kh8 Rxb7+ Kg8 Rg7+ Kh8 Rg5+ Kh7 Rxh5 Kg6 Rh3 Kxf6 Rxh6+ Kg5 Rh3 Reb8 Rg3+ Kf6 Rf3+ Kg6 a3 a5 bxa5 Rxa5 Nc4 Rd5 Rf4 Nd7 Rxe6+ Kg5 g3',
    notes: {
      49: 'Bf6!! With the rook already on g3 and the queen on h5, the queen is left hanging. After ...Qxh5 the windmill starts and the queen is recovered with interest.',
      51: 'Rxg7+ Kh8 — the king has to shuttle between h8 and g8 while the rook checks and captures.',
      53: 'Rxf7+ with discovered check from the bishop: the rook takes with impunity because every capture is check.',
      57: 'Rxb7+ — the third pawn or piece the rook has eaten. The bishop on f6 does all the work.',
      61: 'Rg5+ and the rook comes back to take the queen on h5. Count the material: White is two pawns up in a rook ending.',
      65: 'Rh3 keeps the h-pawn: the rest is technique.',
      83: 'Rxe6+ wins another pawn. Lasker resigned two moves later.',
    },
    outro:
      'A windmill needs a bishop (or rook) giving discovered check and a rook that can capture along the rank each time it returns. Whenever a queen sacrifice sets one up, count the material at the end, not at the start.',
  },
  {
    id: 'glucksberg-najdorf',
    title: 'The Polish Immortal',
    white: 'Glücksberg',
    black: 'Miguel Najdorf',
    event: 'Warsaw',
    year: 1930,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 17,
    difficulty: 3,
    intro:
      'Four minor pieces sacrificed in twenty-two moves, and a mate by a pawn. A young Najdorf drags the white king from g1 to g4 and closes the net with a pawn push. One of the wildest attacking games ever played.',
    moves:
      'd4 f5 c4 Nf6 Nc3 e6 Nf3 d5 e3 c6 Bd3 Bd6 O-O O-O Ne2 Nbd7 Ng5 Bxh2+ Kh1 Ng4 f4 Qe8 g3 Qh5 Kg2 Bg1 Nxg1 Qh2+ Kf3 e5 dxe5 Ndxe5+ fxe5 Nxe5+ Kf4 Ng6+ Kf3 f4 exf4 Bg4+ Kxg4 Ne5+ fxe5 h5#',
    notes: {
      18: '...Bxh2+! The first sacrifice. Kxh2 runs into ...Ng4+ followed by ...Qxg5, so the king goes to h1 — and the attack begins.',
      20: '...Ng4 threatens ...Qh4 and mate on h2. White’s f4 opens a square for the king.',
      24: '...Qh5: the queen joins in; the threat is ...Qh2+ or ...Bg3.',
      26: '...Bg1!! A second sacrifice — the bishop is given up to deflect the knight and open the h2-square.',
      32: '...Ndxe5+! The third piece: the knight is offered to pull the king further up the board.',
      34: '...Nxe5+ — the fourth. White cannot decline: every capture comes with check.',
      38: '...f4! A quiet pawn move in a storm — it takes away g3 and prepares ...Bg4+.',
      40: '...Bg4+! The fifth sacrifice: Kxg4 walks into the net.',
      42: '...Ne5+ fxe5 and …',
      44: '…h5 mate. A king on g4, hemmed in by its own pawns and a black pawn on h5.',
    },
    outro:
      'When the king is out in the open, count the attackers, not the material: Najdorf gave up a bishop, a bishop, two knights and a pawn, and still had enough left to mate.',
  },
  {
    id: 'canal-peruvian-immortal',
    title: 'The Peruvian Immortal',
    white: 'Esteban Canal',
    black: 'NN',
    event: 'Budapest (simultaneous display)',
    year: 1934,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 20,
    difficulty: 1,
    intro:
      'Both rooks and the queen sacrificed in fourteen moves, and mate with two minor pieces: Boden’s mate in its purest form. A simultaneous game — but the pattern is worth more than many master games.',
    moves:
      'e4 d5 exd5 Qxd5 Nc3 Qa5 d4 c6 Nf3 Bg4 Bf4 e6 h3 Bxf3 Qxf3 Bb4 Be2 Nd7 a3 O-O-O axb4 Qxa1+ Kd2 Qxh1 Qxc6+ bxc6 Ba6#',
    notes: {
      21: 'axb4! Castling long looked safe, but the bishop on b4 is loose. A rook is offered: the pin on the c3-knight is broken and the queen is dragged to a1.',
      23: 'Kd2 — the second rook is left hanging too. White wants the queen as far from c6 as possible.',
      25: 'Qxc6+!! The queen goes as well. After ...bxc6 the diagonals to the king are open …',
      27: '…and Ba6 is mate: the bishop on f4 covers b8 and c7, the bishop on a6 covers c8. Boden’s mate.',
    },
    outro:
      'Everything White sacrificed was on the other side of the board from the mate. Look for Boden’s mate whenever a king castles long behind pawns on c6 and d7 and your bishops point at c8 and c7.',
  },
  {
    id: 'fischer-reshevsky-1958',
    title: 'A queen trapped on move 11',
    white: 'Robert James Fischer',
    black: 'Samuel Reshevsky',
    event: 'US Championship, New York',
    year: 1958,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 16,
    difficulty: 2,
    intro:
      'Fifteen-year-old Fischer catches the many-times US champion in an opening trap: a bishop sacrifice on f7 and a knight on e6 win the queen for two pieces. Then he converts — the harder part.',
    moves:
      'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6 Be3 Bg7 Nc3 Nf6 Bc4 O-O Bb3 Na5 e5 Ne8 Bxf7+ Kxf7 Ne6 dxe6 Qxd8 Nc6 Qd2 Bxe5 O-O Nd6 Bf4 Nc4 Qe2 Bxf4 Qxc4 Kg7 Ne4 Bc7 Nc5 Rf6 c3 e5 Rad1 Nd8 Nd7 Rc6 Qh4 Re6 Nc5 Rf6 Ne4 Rf4 Qxe7+ Rf7 Qa3 Nc6 Nd6 Bxd6 Rxd6 Bf5 b4 Rff8 b5 Nd8 Rd5 Nf7 Rc5 a6 b6 Be4 Re1 Bc6 Rxc6 bxc6 b7 Rab8 Qxa6 Nd8 Rb1 Rf7 h3 Rfxb7 Rxb7+ Rxb7 Qa8',
    notes: {
      17: 'e5! Black’s ...Na5 was a natural move against the b3-bishop — and a losing one: the knight left the centre, and now the f6-knight has to retreat to e8, after which the combination works.',
      19: 'Bxf7+! Kxf7 Ne6!! The knight attacks the queen and cannot be taken: ...dxe6 Qxd8 wins the queen, and ...Kxe6 walks into Qd5+ with a mating attack.',
      23: 'Qxd8: a queen for two minor pieces. Reshevsky played on for thirty moves.',
      27: 'Castling — safety first, then the technique. Black’s pieces are active but they cannot mate.',
      35: 'Ne4 heads for c5 and d6: the knight is the best piece on the board.',
      51: 'Qxe7+ wins a pawn and keeps the initiative. The queen and knight harass the loose black pieces.',
      59: 'b4! Fischer starts the passed pawn while the black pieces are tied to the king.',
      67: 'b6 — the pawn reaches b6 with the rook behind it and the queen covering everything.',
      83: 'Qa8: the b-pawn will promote or the rook is lost. Reshevsky resigned.',
    },
    outro:
      'Two lessons: the Bxf7+ and Ne6 pattern against a queen on d8 with the king on g8, and the patience to convert a material edge without rushing.',
  },
  {
    id: 'botvinnik-tal-1960',
    title: 'Tal’s knight sacrifice',
    white: 'Mikhail Botvinnik',
    black: 'Mikhail Tal',
    event: 'World Championship, Moscow (game 6)',
    year: 1960,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 37,
    difficulty: 3,
    intro:
      'The game that decided the 1960 match in Tal’s mind. His 21...Nf4!? is “incorrect” by the engine’s count, but it set problems Botvinnik could not solve at the board. A study in practical chess.',
    moves:
      'c4 Nf6 Nf3 g6 g3 Bg7 Bg2 O-O d4 d6 Nc3 Nbd7 O-O e5 e4 c6 h3 Qb6 d5 cxd5 cxd5 Nc5 Ne1 Bd7 Nd3 Nxd3 Qxd3 Rfc8 Rb1 Nh5 Be3 Qb4 Qe2 Rc4 Rfc1 Rac8 Kh2 f5 exf5 Bxf5 Ra1 Nf4 gxf4 exf4 Bd2 Qxb2 Rab1 f3 Rxb2 fxe2 Rb3 Rd4 Be1 Be5+ Kg1 Bf4 Nxe2 Rxc1 Nxd4 Rxe1+ Bf1 Be4 Ne2 Be5 f4 Bf6 Rxb7 Bxd5 Rc7 Bxa2 Rxa7 Bc4 Ra8+ Kf7 Ra7+ Ke6 Ra3 d5 Kf2 Bh4+ Kg2 Kd6 Ng3 Bxg3 Bxc4 dxc4 Kxg3 Kd5 Ra7 c3 Rc7 Kd4 Rd7+',
    notes: {
      38: '...f5! opens the f-file and the diagonal for the bishop: Tal wants the white king.',
      42: '...Nf4!? The famous sacrifice. Objectively White can defend, but every line demands exact moves.',
      44: '...exf4: the pawn on f4 takes away g3 and e3 from the white pieces, and the g-file is open.',
      46: '...Qxb2! A second surprise: the queen attacks the rook on b1, and after Rab1 the pawn push ...f3 hits the queen on e2 — both white pieces are loose at once.',
      48: '...f3! The point: the pawn attacks the queen on e2, and after Rxb2 fxe2 Black has a rook and a pawn on e2 for the queen — and the initiative.',
      52: '...Rd4! centralises and hits the bishop on d2; Black’s pieces are the active ones.',
      54: '...Be5+ and ...Bf4: the bishop takes the long diagonal with tempo.',
      58: '...Rxc1 and ...Rxe1+: the exchanges leave Black with two bishops and pawns against a rook and knight.',
      68: '...Bxd5, ...Bxa2: the bishops collect the loose pawns while the white rook only collects Black’s.',
      84: '...Bxg3! trades into a won pawn ending: the c-pawn runs.',
      92: '...Kd4 and the c-pawn cannot be stopped. Botvinnik resigned after 47.Rd7+.',
    },
    outro:
      'Tal’s sacrifice was not a bluff: it created problems every move, in a match with a clock ticking. Sometimes the practical decision beats the objective one.',
  },
  {
    id: 'karpov-unzicker-1974',
    title: 'Karpov’s bishop on a7',
    white: 'Anatoly Karpov',
    black: 'Wolfgang Unzicker',
    event: 'Olympiad, Nice',
    year: 1974,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 40,
    difficulty: 3,
    intro:
      'A textbook on closed positions. Karpov closes the centre with d5, strikes first on the queenside with a4, shuts it with a bishop on a7 and doubles rooks on the a-file so that nothing can move, then opens the other side of the board at his leisure. Unzicker never gets a single active move.',
    moves:
      'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Na5 Bc2 c5 d4 Qc7 Nbd2 Nc6 d5 Nd8 a4 Rb8 axb5 axb5 b4 Nb7 Nf1 Bd7 Be3 Ra8 Qd2 Rfc8 Bd3 g6 Ng3 Bf8 Ra2 c4 Bb1 Qd8 Ba7 Ne8 Bc2 Nc7 Rea1 Qe7 Bb1 Be8 Ne2 Nd8 Nh2 Bg7 f4 f6 f5 g5 Bc2 Bf7 Ng3 Nb7 Bd1 h6 Bh5 Qe8 Qd1 Nd8 Ra3 Kf8 R1a2 Kg8 Ng4 Kf8 Ne3 Kg8 Bxf7+ Nxf7 Qh5 Nd8 Qg6 Kf8 Nh5',
    notes: {
      43: 'Ra2 prepares to double on the open file. Black can only wait.',
      47: 'Ba7!! The bishop takes away b8 from the rooks and the whole a-file belongs to White. It cannot be attacked.',
      51: 'Rea1: doubled rooks on the file nobody else can use. Black’s pieces are tied to defending the a8-square.',
      59: 'f4! Now the other wing. With the queenside paralysed, White opens the kingside at will.',
      61: 'f5 gains space and fixes the black pawns; the g6-square and the h5-square are now targets.',
      67: 'Bd1–h5: the bishop swaps itself for Black’s best defender.',
      73: 'Ra3 and R1a2 — the rooks keep the a-file while the pieces regroup. No hurry.',
      81: 'Bxf7+ removes the defender of g6, and the queen comes in: Qh5, Qg6.',
      87: 'Nh5 — the knight cannot be taken and Ng7 or Nxf6 is coming. Unzicker resigned.',
    },
    outro:
      'Karpov’s method: fix one side of the board so the opponent has no play, then open the other side. The bishop on a7 is the picture to remember — a piece that does nothing except stop everything.',
  },
];
