import type { ClassicGame } from './games';

/** Fifteen more classics: king hunts, quiet masterpieces and the endings that defined technique. */
export const CLASSIC_GAMES_2: readonly ClassicGame[] = [
  {
    id: 'lasker-thomas',
    title: 'The king walk',
    white: 'Edward Lasker',
    black: 'Sir George Thomas',
    event: 'London (casual)',
    year: 1912,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 18,
    difficulty: 1,
    intro:
      'The most famous king hunt in chess: a queen sacrifice on h7 drags the black king all the way down the board to be mated on g1 — by a quiet king move. Every white move from the sacrifice on is a check, so guess them all.',
    moves:
      'd4 e6 Nf3 f5 Nc3 Nf6 Bg5 Be7 Bxf6 Bxf6 e4 fxe4 Nxe4 b6 Ne5 O-O Bd3 Bb7 Qh5 Qe7 Qxh7+ Kxh7 Nxf6+ Kh6 Neg4+ Kg5 h4+ Kf4 g3+ Kf3 Be2+ Kg2 Rh2+ Kg1 Kd2#',
    notes: {
      19: 'Qh5 aims at h7 with the knight on e5 covering g6 and f7. The threat is already Qxh7 mate if the bishop on f6 were not there — so it is removed first.',
      21: 'Qxh7+!! The queen goes, and the king must take: every escape square is covered.',
      23: 'Nxf6+ discovers the bishop on d3 and opens the way: the king cannot go back to h8 (Ng6 mate), so it must walk forward.',
      25: 'Neg4+ — the second knight joins. From g4 it covers h6 and f6, pushing the king to g5.',
      27: 'h4+ takes g5 away. Notice how each check leaves the king exactly one square.',
      29: 'g3+ — the pawns join the hunt; f4 is no longer available.',
      31: 'Be2+ forces the king to g2, deep inside White’s camp.',
      33: 'Rh2+ pushes the king to the first rank…',
      35: '…and Kd2 is mate: a quiet king move that opens the queen’s rook onto the first rank. The most beautiful mating move in chess.',
    },
    outro:
      'Lasker later said he had also seen O-O-O mate, which would have been even funnier — but castling to deliver mate has a rule problem of its own.',
  },
  {
    id: 'levitsky-marshall',
    title: 'The gold coins game',
    white: 'Stefan Levitsky',
    black: 'Frank Marshall',
    event: 'Breslau',
    year: 1912,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 17,
    difficulty: 2,
    intro:
      'Legend says the spectators showered the board with gold coins after Marshall’s last move — a queen placed where three pieces can take it. Whether the coins are true or not, the move is real. You guess Black from move 9.',
    moves:
      'd4 e6 e4 d5 Nc3 c5 Nf3 Nc6 exd5 exd5 Be2 Nf6 O-O Be7 Bg5 O-O dxc5 Be6 Nd4 Bxc5 Nxe6 fxe6 Bg4 Qd6 Bh3 Rae8 Qd2 Bb4 Bxf6 Rxf6 Rad1 Qc5 Qe2 Bxc3 bxc3 Qxc3 Rxd5 Nd4 Qh5 Ref8 Re5 Rh6 Qg5 Rxh3 Rc5 Qg3',
    notes: {
      18: 'Be6 develops and covers d5; Marshall wants the f-file open, so the bishop will not stay long.',
      20: 'Bxc5 recaptures and eyes f2: the bishop and the f-file will work together all game.',
      22: 'fxe6 opens the f-file for the rook — Marshall wants the f2 square.',
      24: 'Qd6 defends e6 and c5 and keeps an eye on h2.',
      26: 'Rae8 brings the last piece into play; every black piece now points at White’s kingside.',
      28: 'Bb4 pins the knight so that the queen can take on c3 later.',
      30: 'Rxf6 keeps the f-file rather than the pawn structure: activity over structure.',
      32: 'Qc5 lines up with the bishop on b4 against c3 and threatens Qxc3.',
      34: 'Bxc3 removes the defender…',
      36: '…and Qxc3 takes the pawn. White’s next move, Rxd5, walks into the storm.',
      38: 'Nd4! The knight attacks the queen and c2, and blocks the d-file. White’s pieces are now all on the wrong squares.',
      40: 'Ref8 doubles on the f-file: Rxf2 is in the air.',
      42: 'Rh6! attacks the queen and the bishop on h3 at the same time.',
      44: 'Rxh3 wins a piece — but Marshall is not done.',
      46: 'Qg3!!! The queen can be taken three ways and all three lose: hxg3 Ne2+ and Rxf1 mate; fxg3 Ne2+ Kh1 Rxf1 mate; Qxg3 Ne2+ Kh1 Nxg3+ and Black wins a rook with the knight recapturing safely.',
    },
    outro:
      'Three captures, three losses. Qg3 is remembered because every refutation is a different pattern: a knight fork with check, a back-rank mate and a smothered king on h1.',
  },
  {
    id: 'reti-bogoljubov',
    title: 'The two bishops',
    white: 'Richard Réti',
    black: 'Efim Bogoljubov',
    event: 'New York',
    year: 1924,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 22,
    difficulty: 2,
    intro:
      'A quiet Réti Opening becomes one of the most elegant finishes ever: a bishop check on f7 and then a bishop retreat to e8 that wins a whole rook. The brilliancy prize of New York 1924. You guess White from move 12.',
    moves:
      'Nf3 Nf6 c4 e6 g3 d5 Bg2 Bd6 O-O O-O b3 Re8 Bb2 Nbd7 d4 c6 Nbd2 Ne4 Nxe4 dxe4 Ne5 f5 f3 exf3 Bxf3 Qc7 Nxd7 Bxd7 e4 e5 c5 Bf8 Qc2 exd4 exf5 Rad8 Bh5 Re5 Bxd4 Rxf5 Rxf5 Bxf5 Qxf5 Rxd4 Rf1 Rd8 Bf7+ Kh8 Be8',
    notes: {
      23: 'f3! challenges the e4 pawn at once; the long diagonal is about to open for the g2 bishop.',
      25: 'Bxf3 recaptures with the bishop, which now looks straight at the black king and the d5 square.',
      27: 'Nxd7 trades the knight to leave Black with a bishop that has little to do.',
      29: 'e4! Both bishops now point at the kingside and e4-e5 or exf5 is coming.',
      31: 'c5 gains a tempo on the bishop and fixes the c6 pawn — the light-squared bishop’s target.',
      33: 'Qc2 recaptures nothing yet: the queen goes to the b1–h7 diagonal, behind the pawn advance.',
      35: 'exf5 opens the f-file and the diagonal at the same time.',
      37: 'Bh5! attacks the rook on e8 and vacates f3 for the queen. Black’s pieces begin to trip over each other.',
      39: 'Bxd4 takes the pawn with the other bishop and keeps everything protected.',
      41: 'Rxf5 — the exchanges begin, and each one leaves Black with a worse piece.',
      43: 'Qxf5 recaptures and centralises the queen with an eye on f7 and f8.',
      45: 'Rf1 threatens Qf7+ and the back rank. Black defends the d8 rook…',
      47: 'Bf7+! drives the king into the corner.',
      49: 'Be8!! The bishop cannot be taken (the rook on f8 would be lost to the queen), and there is no defence to the double threat on the rook on d8 and mate on f8.',
    },
    outro:
      'Réti collected the brilliancy prize. Note how many quiet moves it took before the two bishops did anything spectacular.',
  },
  {
    id: 'bernstein-capablanca',
    title: 'Capablanca’s Qb2',
    white: 'Ossip Bernstein',
    black: 'José Raúl Capablanca',
    event: 'Moscow',
    year: 1914,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 23,
    difficulty: 2,
    intro:
      'Capablanca defends the Queen’s Gambit, gets a passed pawn on c3 and lets his opponent win it — because he has seen a queen move that wins on the spot. You guess Black from move 12.',
    moves:
      'd4 d5 c4 e6 Nc3 Nf6 Nf3 Be7 Bg5 O-O e3 Nbd7 Rc1 b6 cxd5 exd5 Qa4 Bb7 Ba6 Bxa6 Qxa6 c5 Bxf6 Nxf6 dxc5 bxc5 O-O Qb6 Qe2 c4 Rfd1 Rfd8 Nd4 Bb4 b3 Rac8 bxc4 dxc4 Rc2 Bxc3 Rxc3 Nd5 Rc2 c3 Rdc1 Rc5 Nb3 Rc6 Nd4 Rc7 Nb5 Rc5 Nxc3 Nxc3 Rxc3 Rxc3 Rxc3 Qb2',
    notes: {
      24: 'Nxf6 recaptures with the knight; the hanging pawns on c5 and d5 will become a passed pawn.',
      26: 'bxc5 — Capablanca accepts hanging pawns, planning to push c4 and get a passed c-pawn.',
      28: 'Qb6 covers c5 and eyes b2 and f2.',
      30: 'c4! The pawns advance; the passed pawn is born.',
      32: 'Rfd8 supports d5 and lines up on the d-file.',
      34: 'Bb4 pins the knight on c3 against nothing yet — but it will make the c3 square a battlefield.',
      36: 'Rac8 completes development; every black piece supports the passed pawn.',
      38: 'dxc4 recaptures and the c-pawn becomes protected and passed.',
      40: 'Bxc3 trades off the blockader…',
      42: 'Nd5 hits the rook on c3 and c3 is weak.',
      44: 'c3! The pawn advances to the third rank — apparently to be surrounded and lost.',
      46: 'Rc5 protects c3 from the side.',
      48: 'Rc6 — a quiet move, shuffling out of the knight’s reach while the pawn stays defended.',
      50: 'Rc7 again; Bernstein’s knight dances and Capablanca waits.',
      52: 'Rc5 — the third rook move. It looks like Black is drifting.',
      54: 'Nxc3: Bernstein takes the pawn, believing the exchanges that follow leave him a pawn up.',
      56: 'Rxc3 — the first recapture.',
      58: 'Qb2!! The point of everything. The queen attacks the rook on c3 and the queen on e2 at once, and the back rank decides: Qxb2 is met by Rd1 mate and Qd1 by Rxd1 mate, so the rook is lost. Bernstein resigned.',
    },
    outro:
      'Capablanca saw 29...Qb2 when he played 22...c3. Seven moves of quiet rook shuffles were the bait.',
  },
  {
    id: 'nimzowitsch-samisch',
    title: 'The immortal zugzwang',
    white: 'Friedrich Sämisch',
    black: 'Aron Nimzowitsch',
    event: 'Copenhagen',
    year: 1923,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 13,
    difficulty: 3,
    intro:
      'White resigns in a middlegame with every piece still on the board, because any move loses material. Nimzowitsch’s own “immortal zugzwang game” — and the best demonstration of his ideas about restriction and blockade. You guess Black from move 7.',
    moves:
      'd4 Nf6 c4 e6 Nf3 b6 g3 Bb7 Bg2 Be7 Nc3 O-O O-O d5 Ne5 c6 cxd5 cxd5 Bf4 a6 Rc1 b5 Qb3 Nc6 Nxc6 Bxc6 h3 Qd7 Kh2 Nh5 Bd2 f5 Qd1 b4 Nb1 Bb5 Rg1 Bd6 e4 fxe4 Qxh5 Rxf2 Qg5 Raf8 Kh1 R8f5 Qe3 Bd3 Rce1 h6',
    notes: {
      14: 'd5 takes the centre: with the bishop on b7 and the knight coming to c6, Black has a solid Queen’s Indian structure.',
      16: 'c6 supports d5 and prepares ...b5 to gain queenside space.',
      18: 'cxd5 recaptures with the pawn, keeping the c-file half open for the rooks.',
      20: 'a6 prepares ...b5: Nimzowitsch wants the queenside to be his.',
      22: 'b5! Space. White’s pieces are slowly being pushed back.',
      24: 'Nc6 develops with a threat against the e5 knight.',
      26: 'Bxc6 recaptures and the bishop now stares at White’s kingside from c6.',
      28: 'Qd7 connects the queen to the bishop on the long diagonal: ...Bb5 and ...f5 are coming.',
      30: 'Nh5! The knight heads for f4 or supports ...f5; the bishop on f4 is asked a question.',
      32: 'f5 grabs the kingside as well. Every white piece is being restricted.',
      34: 'b4 kicks the knight to the edge — restriction, Nimzowitsch’s own word.',
      36: 'Bb5 pins the e2 pawn to the rook on f1: White can no longer play e4 freely.',
      38: 'Bd6 aims at the h2 king and controls the f4 square.',
      40: 'fxe4 — White finally broke with e4, but this pawn now cramps the whole white position.',
      42: 'Rxf2! Takes the pawn with the rook; the knight on h5 was worth it for the invasion.',
      44: 'Raf8 doubles: the f-file belongs to Black.',
      46: 'R8f5 attacks the queen and keeps the rooks connected; the queen has almost no squares.',
      48: 'Bd3 attacks the rook and takes e2 from the queen.',
      50: 'h6!! Zugzwang. White has no move that does not lose: the queen has no squares (any queen move loses it or a rook), the knight is stuck, and after Kh2 there is ...R5f3 winning the queen. Sämisch resigned.',
    },
    outro:
      'Every white piece can move — and every move loses. That is zugzwang in the middlegame, which almost never happens.',
  },
  {
    id: 'adams-torre',
    title: 'The queen on the back rank',
    white: 'Edwin Adams',
    black: 'Carlos Torre',
    event: 'New Orleans',
    year: 1920,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 34,
    difficulty: 2,
    intro:
      'Six queen moves in a row, each offering the queen and each unanswerable, because Black’s queen has to guard the back rank at any price. Probably an analysis rather than a real game — but the pattern is worth knowing. You guess White from move 18.',
    moves:
      'e4 e5 Nf3 d6 d4 exd4 Qxd4 Nc6 Bb5 Bd7 Bxc6 Bxc6 Nc3 Nf6 O-O Be7 Nd5 Bxd5 exd5 O-O Bg5 c6 c4 cxd5 cxd5 Re8 Rfe1 a5 Re2 Rc8 Rae1 Qd7 Bxf6 Bxf6 Qg4 Qb5 Qc4 Qd7 Qc7 Qb5 a4 Qxa4 Re4 Qb5 Qxb7',
    notes: {
      35: 'Qg4!! attacks the queen on d7, which cannot take (Qxg4 Rxe8+ and mate on the back rank) and must stay on the b5–e8 diagonal.',
      37: 'Qc4! Again the queen offers itself: Qxc4 Rxe8+ Rxe8 Rxe8 mate. Black’s queen must keep guarding e8.',
      39: 'Qc7! The third offer: Qxc7 Rxe8+. And now b7 and c8 are attacked as well.',
      41: 'a4! A pawn move that hits the queen: every square on the diagonal is running out.',
      43: 'Re4! The rook joins with the same trick — ...Qxe4 Rxe4 and the back rank still falls.',
      45: 'Qxb7 and the queen has no square left that guards e8. Black resigned: Qb5 is the only defence and Qxb5 removes it.',
    },
    outro:
      'The back-rank weakness turned a queen into a prisoner. Remember the pattern: a defender tied to one square can be attacked again and again.',
  },
  {
    id: 'alekhine-nimzowitsch',
    title: 'Alekhine’s gun',
    white: 'Alexander Alekhine',
    black: 'Aron Nimzowitsch',
    event: 'San Remo',
    year: 1930,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 20,
    difficulty: 3,
    intro:
      'Alekhine lines up two rooks and the queen on the c-file — “Alekhine’s gun” — and Black, with every piece on the board, runs out of moves. The classic example of a bind. You guess White from move 11.',
    moves:
      'e4 e6 d4 d5 Nc3 Bb4 e5 c5 Bd2 Ne7 Nb5 Bxd2+ Qxd2 O-O c3 b6 f4 Ba6 Nf3 Qd7 a4 Nbc6 b4 cxb4 cxb4 Bb7 Nd6 f5 a5 Nc8 Nxb7 Qxb7 a6 Qf7 Bb5 N8e7 O-O h6 Rfc1 Rfc8 Rc2 Qe8 Rac1 Rab8 Qe3 Rc7 Rc3 Qd7 R1c2 Kf8 Qc1 Rbc8 Ba4 b5 Bxb5 Ke8 Ba4 Kd8 h4',
    notes: {
      21: 'a4 starts the queenside expansion: b4 will follow, taking c5 away from Black for ever.',
      23: 'b4! opens the c-file for White and fixes Black’s queenside.',
      25: 'cxb4 recaptures; the c-file is now White’s.',
      27: 'Nd6! The knight lands on the outpost with attacks on b7 and f7.',
      29: 'a5 fixes b6 and prepares a6, burying the bishop on b7.',
      31: 'Nxb7 trades the knight for the bishop that defends the light squares.',
      33: 'a6! The pawn shuts the queen out of the b7 square and cramps the queenside.',
      35: 'Bb5 pins the c6 knight against the queen and takes the c-file square.',
      37: 'O-O — castle, then bring the rooks to the c-file.',
      39: 'Rfc1 — the first gun barrel.',
      41: 'Rc2 makes room for the second rook behind it.',
      43: 'Rac1 — two rooks on the file; the queen will come to c1 behind them.',
      45: 'Qe3 heads for c1 via e3: the gun is being loaded.',
      47: 'Rc3 — the front rook steps up so the queen can slot in behind.',
      49: 'R1c2 — the battery: rook, rook, and now the queen to c1.',
      51: 'Qc1! Alekhine’s gun is assembled. Black cannot defend c6 for ever.',
      53: 'Ba4 threatens Bxc6 winning material; ...b5 is forced and loses a pawn.',
      55: 'Bxb5 takes it.',
      57: 'Ba4 retreats, keeping the pin. Black’s pieces are all tied to the c6 knight.',
      59: 'h4! Zugzwang: Black has no useful move. Any knight move or ...Qd7-e8 loses c6, and pawn moves only make it worse. Nimzowitsch resigned.',
    },
    outro:
      'Nimzowitsch, the great theorist of restriction, was himself restricted into resignation with every piece still on the board.',
  },
  {
    id: 'paulsen-morphy',
    title: 'Morphy’s queen sacrifice',
    white: 'Louis Paulsen',
    black: 'Paul Morphy',
    event: 'New York (First American Chess Congress)',
    year: 1857,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 21,
    difficulty: 3,
    intro:
      'Morphy gives his queen for a bishop to strip the white king of its shelter, then hunts it with rook and bishops. The most famous queen sacrifice of the nineteenth century. You guess Black from move 11.',
    moves:
      'e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5 Bc5 O-O O-O Nxe5 Re8 Nxc6 dxc6 Bc4 b5 Be2 Nxe4 Nxe4 Rxe4 Bf3 Re6 c3 Qd3 b4 Bb6 a4 bxa4 Qxa4 Bd7 Ra2 Rae8 Qa6 Qxf3 gxf3 Rg6+ Kh1 Bh3 Rd1 Bg2+ Kg1 Bxf3+ Kf1 Bg2+ Kg1 Bh3+ Kh1 Bxf2 Qf1 Bxf1 Rxf1 Re2 Ra1 Rh6 d4 Be3',
    notes: {
      22: 'Re6 keeps the rook active on the e-file; the queen will come to d3 to paralyse White’s queenside.',
      24: 'Qd3! The queen sits in the heart of White’s position, tying down the d-pawn and the bishop.',
      26: 'Bb6 keeps the diagonal to f2; the bishop pair aims at White’s king.',
      28: 'bxa4 — Morphy opens the a-file only to bring White’s queen away from the kingside.',
      30: 'Bd7 develops the last piece with the idea ...Rae8, everything pointing at the king.',
      32: 'Rae8 completes the setup. White’s queen has just left the defence with Qa6.',
      34: 'Qxf3!! The queen is given for the bishop: the king’s only defender of the light squares is gone.',
      36: 'Rg6+ — the rook checks on the g-file; the king must go to the corner.',
      38: 'Bh3! threatens ...Bg2+ and ...Bxf3 mate; White has to give up the d1 rook’s protection of f1.',
      40: 'Bg2+ starts the dance: the bishop checks from g2 and h3 while the king shuttles.',
      42: 'Bxf3+ takes the pawn with check.',
      44: 'Bg2+ again — a repetition to gain time (Morphy missed the faster 21...Bg2+ 22.Kg1 Bh3! ideas, but the win never went away).',
      46: 'Bh3+ once more, and the king is back on h1.',
      48: 'Bxf2 wins a second pawn and threatens ...Bg2+ with a discovered attack.',
      50: 'Bxf1 takes the queen after Qf1 tried to block: Black gets queen and pawns for the sacrificed queen.',
      52: 'Re2 — the rook invades the second rank.',
      54: 'Rh6 threatens ...Rxh2 mate. White is a rook down in the fight for the king.',
      56: 'Be3 and mate on h2 cannot be stopped. Paulsen resigned.',
    },
    outro:
      'Later analysis found a quicker win after 21...Bg2+, but the sacrifice itself is sound — and it made Morphy famous overnight.',
  },
  {
    id: 'zukertort-blackburne',
    title: 'The quiet queen move',
    white: 'Johannes Zukertort',
    black: 'Joseph Blackburne',
    event: 'London',
    year: 1883,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 36,
    difficulty: 3,
    intro:
      'A rook is attacked, a queen is threatened, and Zukertort plays a quiet queen move to a square where it can be taken — because every capture allows mate. Steinitz called it one of the most brilliant moves ever played. You guess White from move 19.',
    moves:
      'c4 e6 e3 Nf6 Nf3 b6 Be2 Bb7 O-O d5 d4 Bd6 Nc3 O-O b3 Nbd7 Bb2 Qe7 Nb5 Ne4 Nxd6 cxd6 Nd2 Ndf6 f3 Nxd2 Qxd2 dxc4 Bxc4 d5 Bd3 Rfc8 Rae1 Rc7 e4 Rac8 e5 Ne8 f4 g6 Re3 f5 exf6 Nxf6 f5 Ne4 Bxe4 dxe4 fxg6 Rc2 gxh7+ Kh8 d5+ e5 Qb4 R8c5 Rf8+ Kxh7 Qxe4+ Kg7 Bxe5+ Kxf8 Bg7+ Kg8 Qxe7',
    notes: {
      37: 'e5 gains space and drives the knight to the edge of the board.',
      39: 'f4 — the pawn storm begins. The plan is f5 to open the f-file and the b1–h7 diagonal.',
      41: 'Re3 lifts the rook: it will swing to the kingside via e3.',
      43: 'exf6! en passant — the pawn captures and the knight must recapture, blocking Black’s own pieces.',
      45: 'f5 opens the diagonal for the bishop on d3 and threatens fxg6.',
      47: 'Bxe4 trades the bishop for the knight that blocked everything.',
      49: 'fxg6 rips the pawn cover open.',
      51: 'gxh7+ with check drives the king into the corner — and clears g6 for later.',
      53: 'd5+! A discovered check from the bishop on b2; the e5 block is forced and the long diagonal opens.',
      55: 'Qb4!! The immortal move. The queen offers itself: Qxb4 Bxe5+ Kxh7 Rh3+ Kg6 Rg3+ Kh6 Rf6+ and mate follows. Black cannot take and cannot defend everything.',
      57: 'Rf8+! The rook sacrifice — Kxf8 would allow Bxe5+ and Qxe7; Kxh7 is chosen.',
      59: 'Qxe4+ collects the pawn with check.',
      61: 'Bxe5+ — the bishop finally speaks on the long diagonal.',
      63: 'Bg7+ drives the king back…',
      65: '…and Qxe7 wins the queen. Blackburne resigned.',
    },
    outro:
      'Qb4 works because every line ends on the long diagonal that d5+ opened. Steinitz, no friend of Zukertort, still praised the move without reservation.',
  },
  {
    id: 'spassky-bronstein',
    title: 'The James Bond game',
    white: 'Boris Spassky',
    black: 'David Bronstein',
    event: 'USSR Championship, Leningrad',
    year: 1960,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 28,
    difficulty: 3,
    intro:
      'A King’s Gambit in which Spassky lets a black pawn promote with check and mates anyway. The game appeared in the opening scene of the film From Russia with Love. You guess White from move 15.',
    moves:
      'e4 e5 f4 exf4 Nf3 d5 exd5 Bd6 Nc3 Ne7 d4 O-O Bd3 Nd7 O-O h6 Ne4 Nxd5 c4 Ne3 Bxe3 fxe3 c5 Be7 Bc2 Re8 Qd3 e2 Nd6 Nf8 Nxf7 exf1=Q+ Rxf1 Bf5 Qxf5 Qd7 Qf4 Bf6 N3e5 Qe7 Bb3 Bxe5 Nxe5+ Kh7 Qe4+',
    notes: {
      29: 'Nd6!! The knight is offered: Spassky ignores the pawn on e2, which will promote with check, because the attack on f7 is faster.',
      31: 'Nxf7! A second knight sacrifice: the f7 square is the door to the king, and exf1=Q+ is met by Rxf1 without slowing the attack.',
      33: 'Rxf1 recaptures the new queen. Black is a knight up and lost.',
      35: 'Qxf5 takes the bishop with the queen: now Qxd7? is not the idea — the threat is Nh6+ and Qxf7.',
      37: 'Qf4 keeps the queen on the f-file, eyeing f7 and h6 and covering the knight.',
      39: 'N3e5! The second knight comes to e5 with a discovered attack — Nh6+ and Nd6 are in the air.',
      41: 'Bb3 threatens Nh6+ with the bishop on the g8 diagonal: the king’s escape is gone.',
      43: 'Nxe5+ — a discovered check, and the queen on e7 is attacked.',
      45: 'Qe4+ wins: after ...g6 Rxf8 (or ...Kh8 Qh4) Black loses everything. Bronstein resigned.',
    },
    outro:
      'Spassky calculated 15.Nd6 to the end and let a pawn become a queen with check on the way. Keep the initiative when it is worth more than a queen.',
  },
  {
    id: 'fischer-robert-byrne',
    title: 'The resignation nobody understood',
    white: 'Robert Byrne',
    black: 'Bobby Fischer',
    event: 'US Championship, New York',
    year: 1963,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 23,
    difficulty: 3,
    intro:
      'Byrne resigned in a position where the grandmasters commenting in the press room thought White was winning. Fischer had seen a knight sacrifice, a bishop check and a queen move that ended it all. You guess Black from move 12.',
    moves:
      'd4 Nf6 c4 g6 g3 c6 Bg2 d5 cxd5 cxd5 Nc3 Bg7 e3 O-O Nge2 Nc6 O-O b6 b3 Ba6 Ba3 Re8 Qd2 e5 dxe5 Nxe5 Rfd1 Nd3 Qc2 Nxf2 Kxf2 Ng4+ Kg1 Nxe3 Qd2 Nxg2 Kxg2 d4 Nxd4 Bb7+ Kf1 Qd7',
    notes: {
      24: 'e5! opens the centre: Fischer plays for activity even at the cost of an isolated d-pawn.',
      26: 'Nxe5 recaptures and the knight heads for d3, the hole in White’s position.',
      28: 'Nd3 — a knight on the sixth rank, attacking f2 and b2 and paralysing White.',
      30: 'Nxf2!! The sacrifice: the king is dragged forward and the e3 pawn and the g2 bishop become targets.',
      32: 'Ng4+ — the other knight comes with check and hits e3.',
      34: 'Nxe3 wins the pawn back with a fork of the queen and the bishop.',
      36: 'Nxg2 takes the bishop; White’s king has lost its only cover on the light squares.',
      38: 'd4! The pawn advances to open the long diagonal for the bishop on b7 — Black threatens ...Bb7+ and ...Qd7.',
      40: 'Bb7+ checks on the diagonal the pawn just cleared.',
      42: 'Qd7! Byrne resigned. The threats are ...Qh3+ and mate; after Qf2 there is ...Qh3+ Kg1 Re1+! Rxe1 Bxd4 winning the queen. The commentators were still saying White was better.',
    },
    outro:
      'Fischer wrote that the position after 21...Qd7 is “beyond the horizon” for most players — which is why the resignation surprised the room.',
  },
  {
    id: 'fischer-benko',
    title: 'The quiet rook',
    white: 'Bobby Fischer',
    black: 'Pal Benko',
    event: 'US Championship, New York',
    year: 1963,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 22,
    difficulty: 2,
    intro:
      'Fischer wants to play e5 to open the bishop’s diagonal to h7, but ...f5 would block it. So he puts a rook on f6 first — a rook that can be taken. You guess White from move 12.',
    moves:
      'e4 g6 d4 Bg7 Nc3 d6 f4 Nf6 Nf3 O-O Bd3 Bg4 h3 Bxf3 Qxf3 Nc6 Be3 e5 dxe5 dxe5 f5 gxf5 Qxf5 Nd4 Qf2 Ne8 O-O Nd6 Qg3 Kh8 Qg4 c6 Qh5 Qe8 Bxd4 exd4 Rf6 Kg8 e5 h6 Ne2',
    notes: {
      23: 'Qxf5 recaptures and the queen aims at the kingside from f5.',
      25: 'Qf2 retreats to keep the knight on d4 under attack and defend the e3 bishop.',
      27: 'O-O brings the rook to f1: the f-file is the main road to the black king.',
      29: 'Qg3 eyes g6 and the e5 pawn and leaves f4 for a rook.',
      31: 'Qg4 improves the queen again: from g4 it heads for h5 and watches f5.',
      33: 'Qh5 — the queen arrives next to the king; Qxh7 is prevented only by the knight on d6 covering f7… for now.',
      35: 'Bxd4 removes the knight that guarded f5 and e6 — and the e5 pawn recaptures, blocking the long diagonal.',
      37: 'Rf6!! The rook blocks f6 so that ...f5 is impossible: e5 is coming, and the bishop on d3 will reach h7. Bxf6 loses to e5, discovering mate threats on h7.',
      39: 'e5! The diagonal is open and Qxh7 mate is threatened; ...h6 is the only defence.',
      41: 'Ne2! covers d4 and prepares Rxd6; with the bishop on d3, the queen on h5 and the rook on f6, Black is helpless. Benko resigned.',
    },
    outro:
      'Rf6 is a “blocking sacrifice”: not to win material, but to make sure the opponent can never block a diagonal.',
  },
  {
    id: 'botvinnik-portisch',
    title: 'The rook on c7',
    white: 'Mikhail Botvinnik',
    black: 'Lajos Portisch',
    event: 'Monte Carlo',
    year: 1968,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 30,
    difficulty: 3,
    intro:
      'Botvinnik, fifty-six, sacrifices a rook, then the other, then a knight — all from a quiet English Opening. The attack on the light squares around the black king is a study in how much a bishop on the long diagonal is worth. You guess White from move 16.',
    moves:
      'c4 e5 Nc3 Nf6 g3 d5 cxd5 Nxd5 Bg2 Be6 Nf3 Nc6 O-O Nb6 d3 Be7 a3 a5 Be3 O-O Na4 Nxa4 Qxa4 Bd5 Rfc1 Re8 Rc2 Bf8 Rac1 Nb8 Rxc7 Bc6 R1xc6 bxc6 Rxf7 h6 Rb7 Qc8 Qc4+ Kh8 Nh4 Qxb7 Ng6+ Kh7 Be4 Bd6 Nxe5+ g6 Bxg6+ Kg7 Bxh6+',
    notes: {
      31: 'Rxc7!! A rook for a pawn — the point is that ...Bc6 (forced, to save the bishop from Rxc6) allows a second sacrifice.',
      33: 'R1xc6! The second rook goes for the bishop that guarded the light squares; now the bishop on g2 rules the long diagonal.',
      35: 'Rxf7! A third capture: the rook takes a pawn next to the king and cannot be taken (Kxf7 Qc4+ wins the queen with check on the diagonal).',
      37: 'Rb7 attacks the queen; the rook has eaten two pawns and is still untouchable.',
      39: 'Qc4+ — check along the diagonal that the sacrifices opened.',
      41: 'Nh4! The knight heads for g6 and f5; Botvinnik gives up the rook on b7 for the attack.',
      43: 'Ng6+ forks king and rook — and the bishop is about to join on e4.',
      45: 'Be4 threatens Nxe5 and Bxg6 with discovered attacks everywhere.',
      47: 'Nxe5+ — the knight takes with a discovered check from the bishop.',
      49: 'Bxg6+ — and the pawn shelter is gone.',
      51: 'Bxh6+ wins the queen next (Kxh6 Qh4+ or Rxb7). Portisch resigned.',
    },
    outro:
      'Two rooks and a knight for a mating attack — from an opening that looked like nothing. Botvinnik was proud of this one for the rest of his life.',
  },
  {
    id: 'petrosian-spassky-1966',
    title: 'Petrosian’s exchange sacrifices',
    white: 'Tigran Petrosian',
    black: 'Boris Spassky',
    event: 'World Championship, Moscow (game 10)',
    year: 1966,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 40,
    difficulty: 3,
    intro:
      'Petrosian, the great defender, gives up two exchanges in a row and finishes with a queen sacrifice on h8. The best game of the 1966 world championship. You guess White from move 21.',
    moves:
      'Nf3 Nf6 g3 g6 c4 Bg7 Bg2 O-O O-O Nc6 Nc3 d6 d4 a6 d5 Na5 Nd2 c5 Qc2 e5 b3 Ng4 e4 f5 exf5 gxf5 Nd1 b5 f3 e4 Bb2 exf3 Bxf3 Bxb2 Qxb2 Ne5 Be2 f4 gxf4 Bh3 Ne3 Bxf1 Rxf1 Ng6 Bg4 Nxf4 Rxf4 Rxf4 Be6+ Rf7 Ne4 Qh4 Nxd6 Qg5+ Kh1 Ra7 Bxf7+ Rxf7 Qh8+',
    notes: {
      41: 'Ne3! The first exchange: the knight lets ...Bxf1 happen because the knight on e3 and the bishop on g4 will dominate the light squares.',
      43: 'Rxf1 recaptures. White has a knight for a rook and a wonderful position.',
      45: 'Bg4! The bishop takes the key diagonal and attacks the knight; f5 is White’s square.',
      47: 'Rxf4!! The second exchange sacrifice: the rook takes the knight so that the bishop reaches e6 with check.',
      49: 'Be6+ — the bishop on e6 pins Black’s whole position to the king.',
      51: 'Ne4 brings the knight to the centre with Nf6+ and Nxd6 in the air.',
      53: 'Nxd6 wins a pawn and threatens Nxf7 as well as Qh8 ideas.',
      55: 'Kh1 sidesteps the check calmly — Black’s queen alone cannot do anything.',
      57: 'Bxf7+ removes the last defender of the eighth rank…',
      59: '…and Qh8+!! wins: Kxh8 Nxf7+ forks king and queen. Spassky resigned.',
    },
    outro:
      'Two exchange sacrifices for the light squares, then a queen sacrifice for a knight fork. Petrosian could attack when he wanted to.',
  },
  {
    id: 'deep-blue-kasparov',
    title: 'The machine wins',
    white: 'Deep Blue',
    black: 'Garry Kasparov',
    event: 'Rematch, New York (game 6)',
    year: 1997,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 14,
    difficulty: 2,
    intro:
      'The last game of the match that made history: Kasparov allows a well-known knight sacrifice in the Caro-Kann, apparently believing the computer would not play it. It did. You guess White from move 8.',
    moves:
      'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Ng5 Ngf6 Bd3 e6 N1f3 h6 Nxe6 Qe7 O-O fxe6 Bg6+ Kd8 Bf4 b5 a4 Bb7 Re1 Nd5 Bg3 Kc8 axb5 cxb5 Qd3 Bc6 Bf5 exf5 Rxe7 Bxe7 c4',
    notes: {
      15: 'Nxe6! The thematic sacrifice: for a knight White gets a pawn, an uncastled king and a lasting attack on the light squares.',
      17: 'O-O — develop calmly; the attack does not need to be rushed because Black cannot castle.',
      19: 'Bg6+ forces the king to d8 (…Ke7 loses the queen to Re1 ideas), taking away castling for good.',
      21: 'Bf4 develops with an eye on d6 and c7; every white piece comes into the game.',
      23: 'a4! opens lines on the queenside where the king lives.',
      25: 'Re1 attacks the pinned e6 pawn and lines up against the queen.',
      27: 'Bg3 keeps the bishop safe and the d6 square covered.',
      29: 'axb5 opens the a-file; the queenside collapses.',
      31: 'Qd3 threatens Qxb5 and Bf5, and the c-file is about to open too.',
      33: 'Bf5! offers the bishop to open the e-file: exf5 allows Rxe7.',
      35: 'Rxe7 wins the queen for a rook and bishop…',
      37: '…and c4 threatens cxb5 and Qxb5 with a crushing attack. Kasparov resigned after 19 moves.',
    },
    outro:
      'The shortest decisive game of the match — and the last of a human world champion against a computer in a classical match he could still hope to win.',
  },
];
