import type { LongColor } from '@/chess/types';
import { CLASSIC_GAMES_2 } from './games2';
import { CLASSIC_GAMES_3 } from './games3';

export interface ClassicGame {
  id: string;
  title: string;
  white: string;
  black: string;
  event: string;
  year: number;
  result: '1-0' | '0-1' | '1/2-1/2';
  /** Side whose moves the learner guesses. */
  guessColor: LongColor;
  /** Guessing starts once this many half-moves have been played (the opening is shown). */
  guessFromPly: number;
  intro: string;
  /** Space-separated SAN moves. */
  moves: string;
  /** Notes keyed by 1-based ply of the move they describe (shown after it is played). */
  notes: Record<number, string>;
  /** Closing remark after the last move. */
  outro: string;
  difficulty: 1 | 2 | 3;
}

const CLASSIC_GAMES_1: readonly ClassicGame[] = [
  {
    id: 'opera-game',
    title: 'The Opera Game',
    white: 'Paul Morphy',
    black: 'Duke of Brunswick & Count Isouard',
    event: 'Paris Opera',
    year: 1858,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 6,
    difficulty: 1,
    intro:
      'Played in a box at the Paris opera while Norma was on stage. Morphy develops every piece with tempo and never lets his opponents breathe — the perfect first game to study.',
    moves:
      'e4 e5 Nf3 d6 d4 Bg4 dxe5 Bxf3 Qxf3 dxe5 Bc4 Nf6 Qb3 Qe7 Nc3 c6 Bg5 b5 Nxb5 cxb5 Bxb5+ Nbd7 O-O-O Rd8 Rxd7 Rxd7 Rd1 Qe6 Bxd7+ Nxd7 Qb8+ Nxb8 Rd8#',
    notes: {
      11: 'Two attacks at once: the bishop hits f7 and the queen will come to b3 to hit both b7 and f7.',
      13: 'Qb3 threatens Qxf7+ and Qxb7. Black must defend with the queen, tying it down.',
      15: 'Morphy refuses to grab the b7-pawn. Development first: every piece into the game before cashing in.',
      17: 'The pin on the f6-knight paralyses Black.',
      19: 'A piece sacrifice to rip open the queenside — Black’s king is still in the centre.',
      23: 'Castling long brings the rook to the open d-file with check-like effect: the pinned knight on d7 is the target.',
      25: 'The exchange sacrifice removes the defender of the d-file and keeps the initiative.',
      27: 'The last piece joins the attack. Every white piece is working; most black pieces never moved.',
      31: 'The famous queen sacrifice: Qb8+ forces the knight to block…',
      33: '…and the rook mates on d8. A lesson in development and open lines.',
    },
    outro:
      'Seventeen moves. Count Black’s undeveloped pieces at the end — the rook on h8 and bishop on f8 never moved.',
  },
  {
    id: 'immortal-game',
    title: 'The Immortal Game',
    white: 'Adolf Anderssen',
    black: 'Lionel Kieseritzky',
    event: 'London (casual)',
    year: 1851,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 8,
    difficulty: 3,
    intro:
      'Anderssen gives up a bishop, both rooks and the queen — and mates with the three minor pieces he has left. Romantic chess at its most extreme.',
    moves:
      'e4 e5 f4 exf4 Bc4 Qh4+ Kf1 b5 Bxb5 Nf6 Nf3 Qh6 d3 Nh5 Nh4 Qg5 Nf5 c6 g4 Nf6 Rg1 cxb5 h4 Qg6 h5 Qg5 Qf3 Ng8 Bxf4 Qf6 Nc3 Bc5 Nd5 Qxb2 Bd6 Bxg1 e5 Qxa1+ Ke2 Na6 Nxg7+ Kd8 Qf6+ Nxf6 Be7#',
    notes: {
      21: 'Anderssen lets the bishop go: the rook on g1 and the coming h4 start a hunt of the black queen.',
      23: 'h4! chases the queen with gain of time — every tempo is spent on development or attack.',
      27: 'Qf3 threatens Bxf4 winning the queen, so Black retreats the knight to the back rank.',
      33: 'Nd5 walks into ...Qxb2 on purpose. Anderssen has seen that the rook on a1 does not matter.',
      35: 'Bd6!! The bishop cuts off the queen from the defence and threatens Nxg7+ followed by mate.',
      37: 'e5 blocks the queen’s diagonal back to the kingside. Black is a rook and bishop up, and lost.',
      41: 'Nxg7+ draws the king onto the fatal diagonal.',
      43: 'The final queen sacrifice deflects the knight.',
      45: 'Be7 mate with bishop, knight and knight. White gave up everything else.',
    },
    outro:
      'The moral: material only matters if it takes part in the game. Black’s queenside pieces watched from the sidelines.',
  },
  {
    id: 'evergreen-game',
    title: 'The Evergreen Game',
    white: 'Adolf Anderssen',
    black: 'Jean Dufresne',
    event: 'Berlin',
    year: 1852,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 14,
    difficulty: 3,
    intro:
      'From an Evans Gambit, Anderssen builds up against the black king in the centre and finishes with one of the most beautiful combinations ever played.',
    moves:
      'e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4 exd4 O-O d3 Qb3 Qf6 e5 Qg6 Re1 Nge7 Ba3 b5 Qxb5 Rb8 Qa4 Bb6 Nbd2 Bb7 Ne4 Qf5 Bxd3 Qh5 Nf6+ gxf6 exf6 Rg8 Rad1 Qxf3 Rxe7+ Nxe7 Qxd7+ Kxd7 Bf5+ Ke8 Bd7+ Kf8 Bxe7#',
    notes: {
      15: 'Qb3 hits f7 and starts the pressure on the diagonal.',
      17: 'e5 gains space and shuts the black queen out of the defence of the kingside.',
      21: 'Ba3 pins the e7-knight against the king that is still on e8.',
      29: 'Ne4 heads for f6 — the knight sacrifice will rip open the king’s cover.',
      31: 'Bxd3 finally collects the pawn, with the bishop now aiming at h7 and f5.',
      33: 'Nf6+! forces open the g-file.',
      37: 'Rad1!! — the quiet move of the century. White ignores the threat to f3 and prepares Rxe7+.',
      39: 'Rxe7+ begins the combination; the knight must recapture.',
      41: 'Qxd7+!! the queen sacrifice that made the game famous.',
      45: 'Bd7+ and the king has only one square.',
      47: 'Bxe7 mate. The rook on d1 keeps the king from escaping via d8.',
    },
    outro:
      'Rad1 is the move to remember: preparing a combination can be stronger than starting it.',
  },
  {
    id: 'rotlewi-rubinstein',
    title: 'Rubinstein’s Immortal',
    white: 'Georg Rotlewi',
    black: 'Akiba Rubinstein',
    event: 'Łódź',
    year: 1907,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 21,
    difficulty: 3,
    intro:
      'Rubinstein, playing Black, takes over the long diagonal and unleashes a queen sacrifice followed by a rook sacrifice — all calculated to the end.',
    moves:
      'd4 d5 Nf3 e6 e3 c5 c4 Nc6 Nc3 Nf6 dxc5 Bxc5 a3 a6 b4 Bd6 Bb2 O-O Qd2 Qe7 Bd3 dxc4 Bxc4 b5 Bd3 Rd8 Qe2 Bb7 O-O Ne5 Nxe5 Bxe5 f4 Bc7 e4 Rac8 e5 Bb6+ Kh1 Ng4 Be4 Qh4 g3 Rxc3 gxh4 Rd2 Qxd2 Bxe4+ Qg2 Rh3',
    notes: {
      26: 'Rd8 — the rook faces the queen on the d-file, a tactical motif that pays off later.',
      28: 'Bb7 completes the battery on the long diagonal aimed at g2.',
      30: 'Ne5 forces exchanges that leave Black’s bishops raking the board.',
      36: 'Rac8: every black piece is on an open file or diagonal.',
      38: 'Bb6+ drives the king into the corner where the g2-square becomes the target.',
      40: 'Ng4 attacks h2 and f2 and adds a fourth piece to the attack.',
      42: 'Qh4 threatens Qxh2 mate. White must defend with g3.',
      44: 'Rxc3!! The queen is hanging and Black ignores it.',
      46: 'Rd2!! A second sacrifice: the rook attacks the queen and prepares Bxe4+.',
      48: 'Bxe4+ and the queen must block.',
      50: 'Rh3 — mate on h2 cannot be stopped. White resigned.',
    },
    outro:
      'Every black piece took part. Ask yourself at each move: which of my pieces is not yet attacking?',
  },
  {
    id: 'lasker-bauer',
    title: 'The Double Bishop Sacrifice',
    white: 'Emanuel Lasker',
    black: 'Johann Bauer',
    event: 'Amsterdam',
    year: 1889,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 20,
    difficulty: 2,
    intro:
      'The original “Lasker double bishop sacrifice”: two bishops are given up on h7 and g7 to strip the king bare, then a quiet queen move wins a piece back with interest.',
    moves:
      'f4 d5 e3 Nf6 b3 e6 Bb2 Be7 Bd3 b6 Nc3 Bb7 Nf3 Nbd7 O-O O-O Ne2 c5 Ng3 Qc7 Ne5 Nxe5 Bxe5 Qc6 Qe2 a6 Nh5 Nxh5 Bxh7+ Kxh7 Qxh5+ Kg8 Bxg7 Kxg7 Qg4+ Kh7 Rf3 e5 Rh3+ Qh6 Rxh6+ Kxh6 Qd7 Bf6 Qxb7 Kg7 Rf1 Rab8 Qd7 Rfd8 Qg4+ Kf8 fxe5 Bg7 e6 Rb7 Qg6 f6 Rxf6+ Bxf6 Qxf6+ Ke8 Qh8+ Ke7 Qg7+ Kxe6 Qxb7 Rd6 Qxa6 d4 exd4 cxd4 h4 d3 Qxd3',
    notes: {
      21: 'Ne5 offers a trade that leaves the dark-squared bishop pointing at g7.',
      27: 'Nh5! removes the f6-knight, the only defender of h7.',
      29: 'Bxh7+ — the first bishop sacrifice. The king must take.',
      31: 'Qxh5+ forces the king back to g8, where the second bishop strikes.',
      33: 'Bxg7! The second bishop sacrifice. Kxg7 is forced or Qh8 mates.',
      35: 'Qg4+ and the rook lift Rf3 will decide.',
      37: 'Rf3 threatens Rh3+ with mate; Black must give up the queen.',
      43: 'Qd7! The point of the whole combination: a double attack on the two bishops wins one of them.',
    },
    outro:
      'The pattern needs three things: bishops on the b1–h7 and a1–h8 diagonals, a queen that can reach h5, and a rook lift. Check for all three before you sacrifice.',
  },
  {
    id: 'steinitz-bardeleben',
    title: 'The Battle of Hastings',
    white: 'Wilhelm Steinitz',
    black: 'Curt von Bardeleben',
    event: 'Hastings',
    year: 1895,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 14,
    difficulty: 2,
    intro:
      'Steinitz keeps the black king in the centre, opens the position while Black is undeveloped, and finishes with a rook that cannot be captured for four moves in a row.',
    moves:
      'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4 exd4 cxd4 Bb4+ Nc3 d5 exd5 Nxd5 O-O Be6 Bg5 Be7 Bxd5 Bxd5 Nxd5 Qxd5 Bxe7 Nxe7 Re1 f6 Qe2 Qd7 Rac1 c6 d5 cxd5 Nd4 Kf7 Ne6 Rhc8 Qg4 g6 Ng5+ Ke8 Rxe7+ Kf8 Rf7+ Kg8 Rg7+ Kh8 Rxh7+',
    notes: {
      19: 'Bg5 pins the bishop and keeps the black king from castling comfortably.',
      27: 'Re1 — the king is stuck on e8 and the e-file is the road in.',
      29: 'Qe2 adds pressure to e7; Black cannot castle because of Qxe7.',
      31: 'Rac1 brings the last piece into play before opening the position.',
      33: 'd5! opens the c-file and the d4-square for the knight while Black is still tangled up.',
      35: 'Nd4 heads for e6, the square in front of the king.',
      37: 'Ne6 forks the queen and rook and cannot be taken: Qxe6 loses to Qxc8+.',
      39: 'Qg4 threatens Qxg7 and Rxe7+ — Black’s pieces are all on the wrong side.',
      41: 'Ng5+ breaks up the defence and forces the king back to the e-file.',
      43: 'Rxe7+!! The rook cannot be taken by the queen (Rxc8+) or the king (Qd7+ and mate).',
      45: 'Rf7+ — the rook keeps checking and still cannot be captured.',
      47: 'Rg7+ continues the dance; note the queen on d7 is protected only by the king.',
      49: 'Rxh7+ and mate follows in every line. Bardeleben left the board rather than resign.',
    },
    outro:
      'Steinitz demonstrated the finish afterwards: 25...Kg8 26. Rg7+ Kh8 27. Qh4+ Kxg7 28. Qh7+ Kf8 29. Qh8+ Ke7 30. Qg7+ Ke8 31. Qg8+ Ke7 32. Qf7+ Kd8 33. Qf8+ Qe8 34. Nf7+ Kd7 35. Qd6 mate.',
  },
  {
    id: 'reti-tartakower',
    title: 'The Queen Sacrifice Miniature',
    white: 'Richard Réti',
    black: 'Savielly Tartakower',
    event: 'Vienna',
    year: 1910,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 8,
    difficulty: 1,
    intro:
      'Eleven moves, one queen sacrifice, and a mate that beginners and grandmasters alike have admired for a century. Watch the two bishops and the rook on d1.',
    moves:
      'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nf6 Qd3 e5 dxe5 Qa5+ Bd2 Qxe5 O-O-O Nxe4 Qd8+ Kxd8 Bg5+ Kc7 Bd8#',
    notes: {
      9: 'Qd3 is unusual but sets up the trick: the queen guards e4 and eyes the d-file.',
      13: 'Bd2 blocks the check and, more importantly, prepares castling long with the rook on d1.',
      15: 'O-O-O! The rook arrives on the d-file with the black king still on e8 and the queen on e5.',
      17: 'Qd8+!! The queen sacrifice deflects the king onto the d-file.',
      19: 'Bg5+ is a double check from bishop and rook — the king cannot capture and cannot block.',
      21: 'Bd8 mate. If 10...Ke8, then Rd8 is mate instead.',
    },
    outro:
      'Double check is the strongest move in chess: the king must move, and here it has nowhere good to go.',
  },
  {
    id: 'byrne-fischer',
    title: 'The Game of the Century',
    white: 'Donald Byrne',
    black: 'Bobby Fischer',
    event: 'Rosenwald Memorial, New York',
    year: 1956,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 21,
    difficulty: 3,
    intro:
      'Thirteen-year-old Fischer gives up his queen for a swarm of minor pieces and a rook, then walks the white king across the board to its doom. Every black move from move 11 on is a lesson in piece activity.',
    moves:
      'Nf3 Nf6 c4 g6 Nc3 Bg7 d4 O-O Bf4 d5 Qb3 dxc4 Qxc4 c6 e4 Nbd7 Rd1 Nb6 Qc5 Bg4 Bg5 Na4 Qa3 Nxc3 bxc3 Nxe4 Bxe7 Qb6 Bc4 Nxc3 Bc5 Rfe8+ Kf1 Be6 Bxb6 Bxc4+ Kg1 Ne2+ Kf1 Nxd4+ Kg1 Ne2+ Kf1 Nc3+ Kg1 axb6 Qb4 Ra4 Qxb6 Nxd1 h3 Rxa2 Kh2 Nxf2 Re1 Rxe1 Qd8+ Bf8 Nxe1 Bd5 Nf3 Ne4 Qb8 b5 h4 h5 Ne5 Kg7 Kg1 Bc5+ Kf1 Ng3+ Ke1 Bb4+ Kd1 Bb3+ Kc1 Ne2+ Kb1 Nc3+ Kc1 Rc2#',
    notes: {
      22: 'Na4!! offers a knight: if Qxa4 then Nxe4 and the pins on c3 and the threats down the long diagonal win material back with interest.',
      26: 'Nxe4! attacks the bishop on g5 and the queen cannot easily guard everything — Bxe7 walks into the next shot.',
      30: 'Nxc3 again: Black is simply winning pawns while every white piece is loose.',
      32: 'Rfe8+ drives the king to f1, where it will be harassed by knight checks for the rest of the game.',
      34: 'Be6!! — the queen is left en prise. Bxb6 allows Bxc4+ and a “windmill” of discovered and knight checks that collects the rook, the bishop and two pawns.',
      36: 'Bxc4+ begins the harvest: with the king on f1 every knight check comes with tempo.',
      38: 'Ne2+, Nxd4+, Ne2+, Nc3+ — the knight hops around the king picking up the d4 pawn on the way.',
      46: 'axb6: the dust settles. Black has a rook, two bishops and a knight for the queen — far too much.',
      50: 'Nxd1 removes the last active white piece. From here Black just needs to avoid a perpetual.',
      70: 'Bc5+ starts the final king hunt: a chain of checks marches the white king from g1 to c1.',
      82: 'Rc2 mate. The bishops on c5 and b3 and the knight on c3 leave the king no square.',
    },
    outro:
      'The queen sacrifice worked because every black piece became active while every white piece was stranded. Count the attackers, not the points.',
  },
  {
    id: 'botvinnik-capablanca',
    title: 'Botvinnik’s Immortal',
    white: 'Mikhail Botvinnik',
    black: 'José Raúl Capablanca',
    event: 'AVRO',
    year: 1938,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 20,
    difficulty: 3,
    intro:
      'A model game for the Nimzo-Indian: Botvinnik accepts doubled pawns for the centre and the bishop pair, builds a huge pawn centre, and finishes with the famous bishop sacrifice on a3 that clears the way for a queen and knight attack.',
    moves:
      'd4 Nf6 c4 e6 Nc3 Bb4 e3 d5 a3 Bxc3+ bxc3 c5 cxd5 exd5 Bd3 O-O Ne2 b6 O-O Ba6 Bxa6 Nxa6 Bb2 Qd7 a4 Rfe8 Qd3 c4 Qc2 Nb8 Rae1 Nc6 Ng3 Na5 f3 Nb3 e4 Qxa4 e5 Nd7 Qf2 g6 f4 f5 exf6 Nxf6 f5 Rxe1 Rxe1 Re8 Re6 Rxe6 fxe6 Kg7 Qf4 Qe8 Qe5 Qe7 Ba3 Qxa3 Nh5+ gxh5 Qg5+ Kf8 Qxf6+ Kg8 e7 Qc1+ Kf2 Qc2+ Kg3 Qd3+ Kh4 Qe4+ Kxh5 Qe2+ Kh4 Qe4+ g4 Qe1+ Kh5',
    notes: {
      25: 'a4 restrains ...b5 and prepares to bring a rook to the e-file: White plays on the wing where Black’s pieces are not.',
      31: 'Rae1 — everything is ready for e4. The doubled c-pawns matter less than the coming pawn roller.',
      37: 'e4! The central break. Black wins the a-pawn but White’s centre pawns now decide the game.',
      39: 'e5 gains space with tempo and takes f6 away from the knight.',
      43: 'f4 prepares f5, cracking open the black king.',
      47: 'f5! Black cannot hold the e6/f-file complex together.',
      51: 'Re6! An exchange offer that clears the e-file and creates the monster passed e-pawn.',
      53: 'fxe6: the pawn on e6 is worth more than a rook.',
      59: 'Ba3!! The immortal move. The bishop is given away to deflect the queen from the defence of f6 and the e7 square.',
      61: 'Nh5+! Deflects the g-pawn and opens the g-file.',
      63: 'Qg5+ — the king is caught between the queen, the passed pawn and the mating threats.',
      67: 'e7! Now the queen must give endless checks, and Botvinnik has calculated that they run out.',
      79: 'g4 blocks the last checking diagonal; Black resigned after Kh5 because Qe1+ no longer helps.',
      81: 'Kh5 — the king finds shelter at last, and the e-pawn queens.',
    },
    outro:
      'A pawn centre is only strong when it moves. Botvinnik prepared e4 for fifteen moves and then never stopped pushing.',
  },
  {
    id: 'karpov-kasparov-1985',
    title: 'The Octopus Knight',
    white: 'Anatoly Karpov',
    black: 'Garry Kasparov',
    event: 'World Championship, Moscow (game 16)',
    year: 1985,
    result: '0-1',
    guessColor: 'black',
    guessFromPly: 15,
    difficulty: 3,
    intro:
      'Kasparov gambits a pawn in the Sicilian and plants a knight on d3 — the “octopus” — where it strangles White’s entire position. A masterclass in playing for squares rather than material.',
    moves:
      'e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6 Nb5 d6 c4 Nf6 N1c3 a6 Na3 d5 cxd5 exd5 exd5 Nb4 Be2 Bc5 O-O O-O Bf3 Bf5 Bg5 Re8 Qd2 b5 Rad1 Nd3 Nab1 h6 Bh4 b4 Na4 Bd6 Bg3 Rc8 b3 g5 Bxd6 Qxd6 g3 Nd7 Bg2 Qf6 a3 a5 axb4 axb4 Qa2 Bg6 d6 g4 Qd2 Kg7 f3 Qxd6 fxg4 Qd4+ Kh1 Nf6 Rf4 Ne4 Qxd3 Nf2+ Rxf2 Bxd3 Rfd2 Qe3 Rxd3 Rc1 Nb2 Qf2 Nd2 Rxd1+ Nxd1 Re1+',
    notes: {
      16: 'd5! The gambit: Black gives a pawn to free every piece and to get the knight to d3.',
      20: 'Nb4 heads for d3, the square the whole game will revolve around.',
      22: 'Bc5 takes the g1–a7 diagonal and stops any d4 ideas.',
      32: 'Nd3!! The octopus. It cannot be taken, and it paralyses both white rooks and the knight on a3.',
      42: 'g5 gains space on the kingside while White has no play at all.',
      48: 'Qf6 eyes f2 and the long diagonal; every black piece has a job.',
      56: 'g4 opens lines around the white king at the moment when White’s pieces are furthest away.',
      62: 'Qd4+ centralises with check — the queen now dominates the whole board.',
      66: 'Ne4! Adds a second knight to the attack and threatens Nf2+.',
      68: 'Nf2+ wins material: the fork works because the octopus on d3 is still untouchable.',
      74: 'Rc1! Pins and threatens Rxd1+; White is helpless.',
      76: 'Qf2 threatens both Qxd2 and Rxd1+. Karpov resigned four moves later.',
      80: 'Re1+ and the rook or the queen falls with mate to follow.',
    },
    outro:
      'One piece on a perfect square can be worth more than a pawn — or a whole army. Look for outposts your opponent can never challenge.',
  },
  {
    id: 'kasparov-topalov',
    title: 'Kasparov’s Immortal',
    white: 'Garry Kasparov',
    black: 'Veselin Topalov',
    event: 'Wijk aan Zee',
    year: 1999,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 24,
    difficulty: 3,
    intro:
      'A rook sacrifice on d4, another rook sacrifice on e7, and a king hunt that drags the black king from a7 to d1 — arguably the most spectacular attacking game of the modern era.',
    moves:
      'e4 d6 d4 Nf6 Nc3 g6 Be3 Bg7 Qd2 c6 f3 b5 Nge2 Nbd7 Bh6 Bxh6 Qxh6 Bb7 a3 e5 O-O-O Qe7 Kb1 a6 Nc1 O-O-O Nb3 exd4 Rxd4 c5 Rd1 Nb6 g3 Kb8 Na5 Ba8 Bh3 d5 Qf4+ Ka7 Rhe1 d4 Nd5 Nbxd5 exd5 Qd6 Rxd4 cxd4 Re7+ Kb6 Qxd4+ Kxa5 b4+ Ka4 Qc3 Qxd5 Ra7 Bb7 Rxb7 Qc4 Qxf6 Kxa3 Qxa6+ Kxb4 c3+ Kxc3 Qa1+ Kd2 Qb2+ Kd1 Bf1 Rd2 Rd7 Rxd7 Bxc4 bxc4 Qxh8 Rd3 Qa8 c3 Qa4+ Ke1 f4 f5 Kc1 Rd2 Qa7',
    notes: {
      35: 'Na5 sets up a knight next to the black king and prepares the combination that follows.',
      39: 'Qf4+ forces the king to a7, where it will be a target for the rest of the game.',
      43: 'Nd5! offers a piece to open the e-file and the long diagonal.',
      47: 'Rxd4!! The first rook sacrifice. If cxd4 then Re7+ and the king must walk out.',
      49: 'Re7+!! The second rook sacrifice — Qxe7 loses to Qxd4+ and mate on the a-file, so the king has to run.',
      51: 'Qxd4+ picks up the pawn with check and keeps driving the king.',
      53: 'b4+ shuts off the retreat; the king is forced to a4 — deep in White’s camp.',
      55: 'Qc3! A quiet move in the middle of a hurricane: it threatens Qb3 mate.',
      57: 'Ra7 threatens Rxa6 mate.',
      59: 'Rxb7 removes the defender and renews the mating net.',
      61: 'Qxf6 wins a piece with the threat of Qxa6+ next.',
      63: 'Qxa6+ — the black king is chased down the board it climbed up.',
      65: 'c3+ Kxc3 — the king has walked from a7 to c3, and it is still not safe.',
      67: 'Qa1+ Kd2 Qb2+ Kd1: the last stop before the finish.',
      71: 'Bf1! A quiet developing move that threatens Qe2 mate and wins the queen.',
      73: 'Rd7! Deflects the rook so that Bxc4 comes with tempo.',
      87: 'Qa7 — the queen ending is hopeless for Black: the c-pawn falls and the h-pawn will queen.',
    },
    outro:
      'Kasparov calculated a forced sequence of more than fifteen moves before playing 24. Rxd4. Long forcing lines are where sacrifices become sound.',
  },
  {
    id: 'capablanca-marshall',
    title: 'Refuting the Marshall Attack',
    white: 'José Raúl Capablanca',
    black: 'Frank Marshall',
    event: 'Manhattan Chess Club, New York',
    year: 1918,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 16,
    difficulty: 3,
    intro:
      'Marshall had kept a gambit secret for years and unleashed it on the world champion-to-be. Capablanca had never seen it, took the pawn, and defended with a calm that still defines the position today. You guess White’s moves from the moment the gambit begins.',
    moves:
      'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 O-O c3 d5 exd5 Nxd5 Nxe5 Nxe5 Rxe5 Nf6 Re1 Bd6 h3 Ng4 Qf3 Qh4 d4 Nxf2 Re2 Bg4 hxg4 Bh2+ Kf1 Bg3 Rxf2 Qh1+ Ke2 Bxf2 Bd2 Bh4 Qh3 Rae8+ Kd3 Qf1+ Kc2 Bf2 Qf3 Qg1 Bd5 c5 dxc5 Bxc5 b4 Bd6 a4 a5 axb5 axb4 Ra6 bxc3 Nxc3 Bb4 b6 Bxc3 Bxc3 h6 b7 Re3 Bxf7+',
    notes: {
      17: 'Take the pawn. Declining with d3 is safe, but Capablanca reasoned that a gambit he had never seen must be met on its merits.',
      25: 'h3 asks the knight a question. Marshall’s answer, Ng4, is the point of his idea: threats on h2 and f2.',
      27: 'Qf3 defends f2 and h3 at once and prepares to give the queen for two pieces if it must. The king will walk, not run.',
      29: 'd4! blocks the diagonal to h2 and frees the bishop. Black’s pieces look menacing but White’s centre is real.',
      31: 'Re2 keeps the rook on the second rank where it shields the king; Rxe7 would open the f-file to Black’s benefit.',
      33: 'hxg4: take the bishop. The knight on f2 is trapped in White’s camp and every black check must be exact.',
      35: 'Kf1, not Kh1 — on h1 the queen would be lost to a discovered check.',
      37: 'Rxf2 gives back the exchange to remove the most dangerous attacker. Material is level and Black’s attack is running out of pieces.',
      39: 'The king steps to e2 and heads for the queenside, where it will be perfectly safe behind its pawns.',
      41: 'Bd2 develops with a threat: the bishop covers e1 and the queen can now go to h3.',
      43: 'Qh3 offers a queen trade. With the attack over, every exchange favours the side with the extra piece.',
      45: 'Kd3 — walking the king across the board in front of the enemy rooks. It works because the black pieces cannot coordinate.',
      47: 'Kc2 reaches shelter. From here White is simply a piece up with a safe king.',
      49: 'Qf3 centralises and pins the bishop against the queen.',
      51: 'Bd5 hits the rook and f7; the bishop pair starts to bite.',
      55: 'b4 gains space on the queenside where White will create a passed pawn.',
      57: 'a4 opens the a-file for the rook that has waited all game.',
      61: 'Ra6 uses the file: the rook attacks along the sixth rank and will support the b-pawn.',
      63: 'Nxc3: the last undeveloped piece enters, and with tempo.',
      65: 'b6 — the passed pawn runs. Black’s attack has vanished and the pawn decides.',
      69: 'b7 and the pawn cannot be stopped.',
      71: 'Bxf7+ wins the queen after Rxf7 b8=Q+. Marshall resigned.',
    },
    outro:
      'Capablanca never panicked: he returned the exchange, walked his king to safety and then used the extra piece. Defending a gambit is about keeping the pieces, not the pawns.',
  },
  {
    id: 'lasker-capablanca-1914',
    title: 'The Exchange Variation, played to win',
    white: 'Emanuel Lasker',
    black: 'José Raúl Capablanca',
    event: 'St Petersburg',
    year: 1914,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 20,
    difficulty: 3,
    intro:
      'Lasker needed a win against the tournament leader and chose the quietest opening imaginable — the Exchange Ruy Lopez with an early queen trade. What followed is the classic demonstration of a knight outpost and slow, patient pressure. You guess White’s moves from move 11.',
    moves:
      'e4 e5 Nf3 Nc6 Bb5 a6 Bxc6 dxc6 d4 exd4 Qxd4 Qxd4 Nxd4 Bd6 Nc3 Ne7 O-O O-O f4 Re8 Nb3 f6 f5 b6 Bf4 Bb7 Bxd6 cxd6 Nd4 Rad8 Ne6 Rd7 Rad1 Nc8 Rf2 b5 Rfd2 Rde7 b4 Kf7 a3 Ba8 Kf2 Ra7 g4 h6 Rd3 a5 h4 axb4 axb4 Rae7 Kf3 Rg8 Kf4 g6 Rg3 g5+ Kf3 Nb6 hxg5 hxg5 Rh3 Rd7 Kg3 Ke8 Rdh1 Bb7 e5 dxe5 Ne4 Nd5 N6c5 Bc8 Nxd7 Bxd7 Rh7 Rf8 Ra1 Kd8 Ra8+ Bc8 Nc5',
    notes: {
      21: 'Nb3 steps back so that the f-pawn can advance and the bishop on c1 gets the long diagonal.',
      23: 'f5! fixes the black pawns on dark squares and takes e6 away from the bishop for ever. The knight will land there.',
      25: 'Bf4 provokes a bishop trade. Without dark-squared bishops the e6 square belongs to White.',
      27: 'Bxd6 completes the trade; note that Black’s c-pawns are now doubled and the d6 pawn is backward.',
      29: 'Nd4 heads for e6 — an outpost that can never be challenged by a pawn.',
      31: 'Ne6 arrives. The knight ties Black’s rooks to defence and cramps the whole position.',
      33: 'Rad1 completes development along the file the knight controls.',
      35: 'Rf2 prepares to double: slow moves are fine when the opponent has no counterplay.',
      39: 'b4 fixes the queenside and prepares a3 and a later break.',
      41: 'a3 — the pawns support each other so that ...a5 never gains anything.',
      43: 'The king is a fighting piece in the endgame. Kf2 begins its march to the centre.',
      45: 'g4 gains space on the kingside; every white pawn move takes squares away from Black.',
      47: 'Rd3 sidesteps the bishop’s diagonal and readies the rook for the h-file.',
      49: 'h4 prepares to open the h-file, the only file where White’s rooks can enter.',
      51: 'axb4 keeps the a-file closed to Black and the structure intact.',
      53: 'Kf3 — closer to the action again.',
      55: 'Kf4 invites ...g6: any pawn move by Black creates new weaknesses.',
      57: 'Rg3 eyes the g-file while the king stays central.',
      59: 'Kf3 retreats in time: the g5 pawn is now fixed as a target.',
      61: 'hxg5 opens the h-file for the rook lift that decides the game.',
      63: 'Rh3 takes the file. Black can only wait.',
      65: 'Kg3 protects everything on the kingside so that both rooks are free.',
      67: 'Rdh1 doubles: the invasion on h7 cannot be prevented.',
      69: 'e5! breaks in the centre while every black piece is tied to the kingside.',
      71: 'Ne4 joins the attack through the square the pawn break opened.',
      73: 'N6c5 wins the exchange: the knight forks rook and bishop and cannot be taken.',
      75: 'Nxd7 collects.',
      77: 'Rh7 — the seventh rank, at last. Every threat now lands.',
      79: 'Ra1 brings the last rook to the open file; the black king has nowhere to go.',
      81: 'Ra8+ drives the king to the corner and Nc5 will win the bishop. Capablanca resigned.',
    },
    outro:
      'No tactics until move 35, and none were needed: an outpost on e6, a fixed pawn structure and a rook lift did the work. Patience is a weapon.',
  },
  {
    id: 'short-timman',
    title: 'The king walk',
    white: 'Nigel Short',
    black: 'Jan Timman',
    event: 'Tilburg',
    year: 1991,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 40,
    difficulty: 2,
    intro:
      'Short’s pieces are already on the kingside; what is missing from the mating net is a defender for the g6 square — so the king goes up the board to provide it, in the middlegame, with queens on. You guess White from move 21.',
    moves:
      'e4 Nf6 e5 Nd5 d4 d6 Nf3 g6 Bc4 Nb6 Bb3 Bg7 Qe2 Nc6 O-O O-O h3 a5 a4 dxe5 dxe5 Nd4 Nxd4 Qxd4 Re1 e6 Nd2 Nd5 Nf3 Qc5 Qe4 Qb4 Bc4 Nb6 b3 Nxc4 bxc4 Re8 Rd1 Qc5 Qh4 b6 Be3 Qc6 Bh6 Bh8 Rd8 Bb7 Rad1 Bg7 R8d7 Rf8 Bxg7 Kxg7 R1d4 Rae8 Qf6+ Kg8 h4 h5 Kh2 Rc8 Kg3 Rce8 Kf4 Bc8 Kg5',
    notes: {
      41: 'Qh4 begins the kingside attack: the queen eyes h6 and f6, and the e5 pawn keeps the black pieces away.',
      43: 'Be3 gains a tempo on the queen and prepares Bh6.',
      45: 'Bh6 forces the bishop into the corner; the dark squares around Black’s king are now White’s.',
      47: 'Rd8 invades the open file — Black’s pieces are too passive to challenge it.',
      49: 'Rad1 doubles on the file. Every white piece is now in the attack.',
      51: 'R8d7 attacks f7 and keeps the rook where it cannot be exchanged.',
      53: 'Bxg7 removes the only defender of the dark squares.',
      55: 'R1d4 lifts the second rook towards the kingside; Rf4 is coming.',
      57: 'Qf6+ forces the king to g8. The queen and the e5 pawn now cover every escape square.',
      59: 'h4! creates a path. The idea is not a pawn storm but a walk: the king will support a mate on g7.',
      61: 'Kh2 — first step. Black has no checks, so the king is safe in the middle of the board.',
      63: 'Kg3 — second step. Nothing can stop it.',
      65: 'Kf4 — third step. Black’s only try, ...Bc8, hopes for ...Bxg4 ideas that never come.',
      67: 'Kg5! Next is Kh6 and Qg7 mate, and there is no defence. Timman resigned.',
    },
    outro:
      'When the opponent has no counterplay, the king can join the attack like any other piece. The walk works because Short first took every open line and every checking square away from Black.',
  },
  {
    id: 'fischer-spassky-1972-6',
    title: 'Fischer’s masterpiece',
    white: 'Bobby Fischer',
    black: 'Boris Spassky',
    event: 'World Championship, Reykjavík (game 6)',
    year: 1972,
    result: '1-0',
    guessColor: 'white',
    guessFromPly: 20,
    difficulty: 3,
    intro:
      'Fischer opened with 1.c4 for the first time in his career and produced a game so clean that Spassky joined the audience in applauding it. Hanging pawns, a minority attack that becomes a central break, and a queen that lands on f4 to finish. You guess White from move 11.',
    moves:
      'c4 e6 Nf3 d5 d4 Nf6 Nc3 Be7 Bg5 O-O e3 h6 Bh4 b6 cxd5 Nxd5 Bxe7 Qxe7 Nxd5 exd5 Rc1 Be6 Qa4 c5 Qa3 Rc8 Bb5 a6 dxc5 bxc5 O-O Ra7 Be2 Nd7 Nd4 Qf8 Nxe6 fxe6 e4 d4 f4 Qe7 e5 Rb8 Bc4 Kh8 Qh3 Nf8 b3 a5 f5 exf5 Rxf5 Nh7 Rcf1 Qd8 Qg3 Re7 h4 Rbb7 e6 Rbc7 Qe5 Qe8 a4 Qd8 R1f2 Qe8 R2f3 Qd8 Bd3 Qe8 Qe4 Nf6 Rxf6 gxf6 Rxf6 Kg8 Bc4 Kh8 Qf4',
    notes: {
      21: 'Rc1 takes the half-open file and prepares pressure on c7 and the c5 break.',
      23: 'Qa4 pins the d7-square: Black cannot develop the knight to d7 without losing a pawn.',
      25: 'Qa3 keeps the pin on the c5 pawn and eyes the e7 square. Black’s queenside is under permanent tension.',
      27: 'Bb5! prevents ...Nd7 again and provokes ...a6, a pawn that will later become a target.',
      29: 'dxc5 creates hanging pawns on c5 and d5 — strong if they advance, weak if they are blockaded.',
      31: 'Castle before doing anything else; the position is calm enough.',
      33: 'Be2 retreats so that the bishop can later come to c4 and attack d5 and e6.',
      35: 'Nd4 threatens the e6 bishop and prepares to trade it, leaving the light squares weak.',
      37: 'Nxe6 removes the bishop; now the e6 pawn and the light squares are chronic weaknesses.',
      39: 'e4! attacks d5 and opens the position while Black’s pieces are tangled.',
      41: 'f4 keeps the initiative; the f-pawn will open the f-file against the king.',
      43: 'e5 fixes the e6 pawn and takes f6 and d6 away from Black’s pieces.',
      45: 'Bc4 hits e6 from the other side. Every white piece has a target.',
      47: 'Qh3 lines up against e6 and h6 — the queen joins the attack via the h-file.',
      49: 'b3 makes room for a4 and shuts down any counterplay on the queenside.',
      51: 'f5! opens the f-file at the cost of a pawn; the rooks get the file, Black gets nothing.',
      53: 'Rxf5 recaptures with the rook, keeping the pressure on f7 and e6.',
      55: 'Rcf1 doubles: the f-file is White’s highway to the king.',
      57: 'Qg3 threatens Qg6 and keeps the h7 knight tied down.',
      59: 'h4 gains space and prepares h5, taking the g6 square.',
      61: 'e6 — the passed pawn advances with tempo, and the black rooks can only shuffle.',
      63: 'Qe5 centralises, attacks d4 and prepares the final regrouping.',
      65: 'a4 — a quiet move that removes Black’s only pawn break. Zugzwang-like: Black has nothing to do.',
      67: 'R1f2 and R2f3: the rooks are rearranged so that the queen can come to e4 with everything protected.',
      69: 'R2f3 completes the battery.',
      71: 'Bd3 aims at h7. Black’s king has three defenders and all of them are pinned to their squares.',
      73: 'Qe4 threatens Qh7 mate and forces ...Nf6, the only defence.',
      75: 'Rxf6! removes the defender. The exchange sacrifice ends the game.',
      77: 'Rxf6 — the other rook takes over the file.',
      79: 'Bc4 pins the e-pawn and takes away f7. Mate is coming on f7 or h7.',
      81: 'Qf4 threatens Rf8 mate and Qf7. Spassky resigned and applauded.',
    },
    outro:
      'From an opening pin to a mating attack, every move improved a piece or created a weakness. Fischer never rushed: the decisive f5 break came only when every piece was ready.',
  },
];

export const CLASSIC_GAMES: readonly ClassicGame[] = [
  ...CLASSIC_GAMES_1,
  ...CLASSIC_GAMES_2,
  ...CLASSIC_GAMES_3,
];

export function getClassicGame(id: string): ClassicGame | undefined {
  return CLASSIC_GAMES.find((g) => g.id === id);
}
