import type { Lesson, LessonCategory, LessonLevel } from './model';
import { lessonStepKeys, type StepKey } from './stepKeys';

/**
 * The files the lessons live in (src/features/learn/lessons/<file>.ts), in
 * curriculum order. Each is its own chunk of the build, loaded when one of its
 * lessons is opened (see lessons/load.ts).
 */
export const LESSON_FILES = [
  'beginner',
  'beginner2',
  'intermediate',
  'intermediate2',
  'intermediate3',
  'intermediate4',
  'intermediate5',
  'intermediate6',
  'advanced',
  'advanced2',
  'advanced3',
  'advanced4',
  'advanced5',
  'advanced6',
] as const;

export type LessonFile = (typeof LESSON_FILES)[number];

/** Everything about a lesson except its steps' content. */
export interface LessonMeta {
  id: string;
  title: string;
  level: LessonLevel;
  category: LessonCategory;
  summary: string;
  minutes: number;
  steps: number;
  tasks: number;
  /** How each step's progress is keyed (its id, or its position): counts progress without the content. */
  stepKeys: StepKey[];
  /** The file that holds the lesson's content. */
  file: LessonFile;
}

export function metaOf(lesson: Lesson, file: LessonFile): LessonMeta {
  return {
    id: lesson.id,
    title: lesson.title,
    level: lesson.level,
    category: lesson.category,
    summary: lesson.summary,
    minutes: lesson.minutes,
    steps: lesson.steps.length,
    tasks: lesson.steps.filter((s) => s.task).length,
    stepKeys: lessonStepKeys(lesson),
    file,
  };
}

/** The source of src/features/learn/lessonMeta.ts (see scripts/build-lesson-index.mjs). */
export function renderLessonMeta(meta: LessonMeta[]): string {
  const rows = meta
    .map(
      (m) =>
        `  ${JSON.stringify({
          id: m.id,
          title: m.title,
          level: m.level,
          category: m.category,
          summary: m.summary,
          minutes: m.minutes,
          steps: m.steps,
          tasks: m.tasks,
          stepKeys: m.stepKeys,
          file: m.file,
        })},`,
    )
    .join('\n');
  return (
    '// GENERATED by scripts/build-lesson-index.mjs — do not edit. Run `npm run lessons:index`.\n' +
    "import type { LessonMeta } from './lessonMetaFormat';\n\n" +
    'export const LESSON_META: readonly LessonMeta[] = [\n' +
    rows +
    '\n];\n\n' +
    'export function getLessonMeta(id: string): LessonMeta | undefined {\n' +
    '  return LESSON_META.find((l) => l.id === id);\n' +
    '}\n'
  );
}
