import type { Lesson, LessonCategory, LessonLevel } from './model';

/** Everything about a lesson except its steps. */
export interface LessonMeta {
  id: string;
  title: string;
  level: LessonLevel;
  category: LessonCategory;
  summary: string;
  minutes: number;
  steps: number;
  tasks: number;
}

export function metaOf(lesson: Lesson): LessonMeta {
  return {
    id: lesson.id,
    title: lesson.title,
    level: lesson.level,
    category: lesson.category,
    summary: lesson.summary,
    minutes: lesson.minutes,
    steps: lesson.steps.length,
    tasks: lesson.steps.filter((s) => s.task).length,
  };
}

/** The source of src/features/learn/lessonMeta.ts (see scripts/build-lesson-index.mjs). */
export function renderLessonMeta(meta: LessonMeta[]): string {
  const rows = meta
    .map(
      (m) =>
        `  ${JSON.stringify({
          id: m.id,
          title: m.title,
          level: m.level,
          category: m.category,
          summary: m.summary,
          minutes: m.minutes,
          steps: m.steps,
          tasks: m.tasks,
        })},`,
    )
    .join('\n');
  return (
    '// GENERATED by scripts/build-lesson-index.mjs — do not edit. Run `npm run lessons:index`.\n' +
    "import type { LessonMeta } from './lessonMetaFormat';\n\n" +
    'export const LESSON_META: readonly LessonMeta[] = [\n' +
    rows +
    '\n];\n\n' +
    'export function getLessonMeta(id: string): LessonMeta | undefined {\n' +
    '  return LESSON_META.find((l) => l.id === id);\n' +
    '}\n'
  );
}
